In [1]:
import pandas as pd
df = pd.read_csv("../data/resumes/Resume.csv")
df.head()

,ID,Resume_str,Resume_html,Category
0,16852973,HR ADMINISTRATOR/MARKETING ASSOCIATE\...,"<div class=""fontsize fontface vmargins hmargin...",HR
1,22323967,"HR SPECIALIST, US HR OPERATIONS ...","<div class=""fontsize fontface vmargins hmargin...",HR
2,33176873,HR DIRECTOR Summary Over 2...,"<div class=""fontsize fontface vmargins hmargin...",HR
3,27018550,HR SPECIALIST Summary Dedica...,"<div class=""fontsize fontface vmargins hmargin...",HR
4,17812897,HR MANAGER Skill Highlights ...,"<div class=""fontsize fontface vmargins hmargin...",HR

In [2]:
df.shape

(2484, 4)

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2484 entries, 0 to 2483
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ID           2484 non-null   int64
 1   Resume_str   2484 non-null   str
 2   Resume_html  2484 non-null   str
 3   Category     2484 non-null   str
dtypes: int64(1), str(3)
memory usage: 52.3 MB

In [4]:
df.isnull().sum()

ID             0
Resume_str     0
Resume_html    0
Category       0
dtype: int64

In [5]:
df["Category"].value_counts()

Category
INFORMATION-TECHNOLOGY    120
BUSINESS-DEVELOPMENT      120
ADVOCATE                  118
CHEF                      118
FINANCE                   118
ENGINEERING               118
ACCOUNTANT                118
FITNESS                   117
AVIATION                  117
SALES                     116
HEALTHCARE                115
CONSULTANT                115
BANKING                   115
CONSTRUCTION              112
PUBLIC-RELATIONS          111
HR                        110
DESIGNER                  107
ARTS                      103
TEACHER                   102
APPAREL                    97
DIGITAL-MEDIA              96
AGRICULTURE                63
AUTOMOBILE                 36
BPO                        22
Name: count, dtype: int64

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
df["ID"].duplicated().sum()

np.int64(0)

In [8]:
df["Category"].value_counts()

Category
INFORMATION-TECHNOLOGY    120
BUSINESS-DEVELOPMENT      120
ADVOCATE                  118
CHEF                      118
FINANCE                   118
ENGINEERING               118
ACCOUNTANT                118
FITNESS                   117
AVIATION                  117
SALES                     116
HEALTHCARE                115
CONSULTANT                115
BANKING                   115
CONSTRUCTION              112
PUBLIC-RELATIONS          111
HR                        110
DESIGNER                  107
ARTS                      103
TEACHER                   102
APPAREL                    97
DIGITAL-MEDIA              96
AGRICULTURE                63
AUTOMOBILE                 36
BPO                        22
Name: count, dtype: int64

In [9]:
print(df["Resume_str"].iloc[0])

         HR ADMINISTRATOR/MARKETING ASSOCIATE

HR ADMINISTRATOR       Summary     Dedicated Customer Service Manager with 15+ years of experience in Hospitality and Customer Service Management.   Respected builder and leader of customer-focused teams; strives to instill a shared, enthusiastic commitment to customer service.         Highlights         Focused on customer satisfaction  Team management  Marketing savvy  Conflict resolution techniques     Training and development  Skilled multi-tasker  Client relations specialist           Accomplishments      Missouri DOT Supervisor Training Certification  Certified by IHG in Customer Loyalty and Marketing by Segment   Hilton Worldwide General Manager Training Certification  Accomplished Trainer for cross server hospitality systems such as    Hilton OnQ  ,   Micros    Opera PMS   , Fidelio    OPERA    Reservation System (ORS) ,   Holidex    Completed courses and seminars in customer service, sales strategies, inventory control, loss prevention, safety, time management, leadership and performance assessment.        Experience      HR Administrator/Marketing Associate

HR Administrator     Dec 2013   to   Current      Company Name   －   City  ,   State     Helps to develop policies, directs and coordinates activities such as employment, compensation, labor relations, benefits, training, and employee services.  Prepares employee separation notices and related documentation  Keeps records of benefits plans participation such as insurance and pension plan, personnel transactions such as hires, promotions, transfers, performance reviews, and terminations, and employee statistics for government reporting.  Advises management in appropriate resolution of employee relations issues.  Administers benefits programs such as life, health, dental, insurance, pension plans, vacation, sick leave, leave of absence, and employee assistance.     Marketing Associate     Designed and created marketing collateral for sales meetings, trade shows and company executives.  Managed the in-house advertising program consisting of print and media collateral pieces.  Assisted in the complete design and launch of the company's website in 2 months.  Created an official company page on Facebook to facilitate interaction with customers.  Analyzed ratings and programming features of competitors to evaluate the effectiveness of marketing strategies.         Advanced Medical Claims Analyst     Mar 2012   to   Dec 2013      Company Name   －   City  ,   State     Reviewed medical bills for the accuracy of the treatments, tests, and hospital stays prior to sanctioning the claims.  Trained to interpret the codes (ICD-9, CPT) and terminology commonly used in medical billing to fully understand the paperwork that is submitted by healthcare providers.  Required to have organizational and analytical skills as well as computer skills, knowledge of medical terminology and procedures, statistics, billing standards, data analysis and laws regarding medical billing.         Assistant General Manager     Jun 2010   to   Dec 2010      Company Name   －   City  ,   State     Performed duties including but not limited to, budgeting and financial management, accounting, human resources, payroll and purchasing.  Established and maintained close working relationships with all departments of the hotel to ensure maximum operation, productivity, morale and guest service.  Handled daily operations and reported directly to the corporate office.  Hired and trained staff on overall objectives and goals with an emphasis on high customer service.  Marketing and Advertising, working on public relations with the media, government and local businesses and Chamber of Commerce.         Executive Support / Marketing Assistant     Jul 2007   to   Jun 2010      Company Name   －   City  ,   State     Provided assistance to various department heads - Executive, Marketing, Customer Service, Human Resources.  Managed front-end operations to ensure friendly and efficient transactions.  Ensured the swift resolution of customer issues to preserve customer loyalty while complying with company policies.  Exemplified the second-to-none customer service delivery in all interactions with customers and potential clients.         Reservation & Front Office Manager     Jun 2004   to   Jul 2007      Company Name   －   City  ,   State          Owner/ Partner     Dec 2001   to   May 2004      Company Name   －   City  ,   State          Price Integrity Coordinator     Aug 1999   to   Dec 2001      Company Name   －   City  ,   State          Education      N/A  ,   Business Administration   1999     Jefferson College   －   City  ,   State       Business Administration  Marketing / Advertising         High School Diploma  ,   College Prep. studies   1998     Sainte Genevieve Senior High   －   City  ,   State       Awarded American Shrubel Leadership Scholarship to Jefferson College         Skills     Accounting, ads, advertising, analytical skills, benefits, billing, budgeting, clients, Customer Service, data analysis, delivery, documentation, employee relations, financial management, government relations, Human Resources, insurance, labor relations, layout, Marketing, marketing collateral, medical billing, medical terminology, office, organizational, payroll, performance reviews, personnel, policies, posters, presentations, public relations, purchasing, reporting, statistics, website.

In [10]:
print(df["Resume_html"].iloc[0])

<div class="fontsize fontface vmargins hmargins linespacing pagesize" id="document"> <div class="section firstsection" id="SECTION_NAME500375979" style="
      padding-top:0px;
    "> <div class="paragraph PARAGRAPH_NAME firstparagraph" id="PARAGRAPH_500375979_1_326506904" style="
      padding-top:0px;
    "> <div class="name" itemprop="name"> <span class="field fName" id="500375979FNAM1"> </span> <span> </span> <span class="field" id="500375979LNAM1"> HR ADMINISTRATOR/MARKETING ASSOCIATE

HR ADMINISTRATOR</span> </div> </div> </div> <div class="section" id="SECTION_SUMM500375981" style="
      padding-top:0px;
    "> <div class="heading bottomborder"> <div class="sectiontitle" id="SECTNAME_SUMM500375981"> Summary</div> </div> <div class="paragraph firstparagraph" id="PARAGRAPH_500375981_1_326506917" style="
      padding-top:0px;
    "> <div class="field singlecolumn" id="500375981FRFM1"> <p align="LEFT"> Dedicated Customer Service Manager with 15+ years of experience in Hospitality and Customer Service Management. </p> <p align="LEFT"> Respected builder and leader of customer-focused teams; strives to instill a shared, enthusiastic commitment to customer service.  </p> </div> </div> </div> <div class="section" id="SECTION_HILT500375982" style="
      padding-top:0px;
    "> <div class="heading bottomborder"> <div class="sectiontitle" id="SECTNAME_HILT500375982"> Highlights</div> </div> <div class="paragraph firstparagraph" id="PARAGRAPH_500375982_1_326509244" style="
      padding-top:0px;
    "> <div class="singlecolumn maincolumn"> <table class="twocol"> <tbody> <tr> <td class="field twocol_1" id="500375982SKC11"> <p align="CENTER"> Focused on customer satisfaction</p> <p align="CENTER"> Team management</p> <p align="CENTER"> Marketing savvy</p> <p align="CENTER"> Conflict resolution techniques</p> <br/> </td> <td class="field twocol_2" id="500375982SKC21"> <p align="CENTER"> Training and development</p> <p align="CENTER"> Skilled multi-tasker</p> <p align="CENTER"> Client relations specialist</p> </td> </tr> </tbody> </table> </div> </div> </div> <div class="section" id="SECTION_ACCM500375993" style="
      padding-top:0px;
    "> <div class="heading bottomborder"> <div class="sectiontitle" id="SECTNAME_ACCM500375993"> Accomplishments</div> </div> <div class="paragraph firstparagraph" id="PARAGRAPH_500375993_1_326506914" style="
      padding-top:0px;
    "> <div class="field singlecolumn" id="500375993FRFM1"> <ul> <li> Missouri DOT Supervisor Training Certification</li> <li> Certified by IHG in Customer Loyalty and Marketing by Segment </li> <li> Hilton Worldwide General Manager Training Certification</li> <li> Accomplished Trainer for cross server hospitality systems such as  <b> <u> Hilton OnQ</u> </b> ,  <u> Micros </u> <b> <u> Opera PMS</u> </b> <u> , Fidelio </u> <b> <u> OPERA</u> </b> <u>  Reservation System (ORS)</u> , <b> <u> Holidex</u> </b> </li> <li> Completed courses and seminars in customer service, sales strategies, inventory control, loss prevention, safety, time management, leadership and performance assessment.</li> </ul> </div> </div> </div> <div class="section" id="SECTION_EXPR500375983" style="
      padding-top:0px;
    "> <div class="heading bottomborder"> <div class="sectiontitle" id="SECTNAME_EXPR500375983"> Experience</div> </div> <div class="paragraph firstparagraph" id="PARAGRAPH_500375983_1_326506906" itemscope="" itemtype="https://schema.org/Organization" style="
      padding-top:0px;
    "> <div class="singlecolumn"> <span class="paddedline"> <span class="jobtitle" id="500375983JTIT1"> HR Administrator/Marketing Associate

HR Administrator</span> <span> </span> <span class="datesWrapper"> <span class="jobdates" format="%b %Y" id="500375983JSTD1"> Dec 2013</span> <span>  to </span> <span class="jobdates" format="%b %Y" id="500375983EDDT1"> Current</span> <br/> </span> </span> <span class="paddedline" itemscope="" itemtype="https://schema.org/postalAddress"> <span class="companyname" id="500375983COMP1" itemprop="name"> Company Name</span> <span>  － </span> <span class="joblocation jobcity" id="500375983JCIT1" itemprop="addressLocality"> City</span> <span> , </span> <span class="joblocation jobstate" id="500375983JSTA1" itemprop="addressRegion"> State</span> </span> <span class="jobline" id="500375983JDES1" itemprop="description"> <ul> <li> Helps to develop policies, directs and coordinates activities such as employment, compensation, labor relations, benefits, training, and employee services.</li> <li> Prepares employee separation notices and related documentation</li> <li> Keeps records of benefits plans participation such as insurance and pension plan, personnel transactions such as hires, promotions, transfers, performance reviews, and terminations, and employee statistics for government reporting.</li> <li> Advises management in appropriate resolution of employee relations issues.</li> <li> Administers benefits programs such as life, health, dental, insurance, pension plans, vacation, sick leave, leave of absence, and employee assistance.</li> </ul> <br/> <p align="LEFT"> <b> Marketing Associate</b>  </p> <ul> <li> Designed and created marketing collateral for sales meetings, trade shows and company executives.</li> <li> Managed the in-house advertising program consisting of print and media collateral pieces.</li> <li> Assisted in the complete design and launch of the company's website in 2 months.</li> <li> Created an official company page on Facebook to facilitate interaction with customers.</li> <li> Analyzed ratings and programming features of competitors to evaluate the effectiveness of marketing strategies.</li> </ul> </span> </div> </div> <div class="paragraph" id="PARAGRAPH_500375983_2_326506907" itemscope="" itemtype="https://schema.org/Organization" style="
      padding-top:10px;
    "> <div class="singlecolumn"> <span class="paddedline"> <span class="jobtitle" id="500375983JTIT2"> Advanced Medical Claims Analyst</span> <span> </span> <span class="datesWrapper"> <span class="jobdates" format="%b %Y" id="500375983JSTD2"> Mar 2012</span> <span>  to </span> <span class="jobdates" format="%b %Y" id="500375983EDDT2"> Dec 2013</span> <br/> </span> </span> <span class="paddedline" itemscope="" itemtype="https://schema.org/postalAddress"> <span class="companyname" id="500375983COMP2" itemprop="name"> Company Name</span> <span>  － </span> <span class="joblocation jobcity" id="500375983JCIT2" itemprop="addressLocality"> City</span> <span> , </span> <span class="joblocation jobstate" id="500375983JSTA2" itemprop="addressRegion"> State</span> </span> <span class="jobline" id="500375983JDES2" itemprop="description"> <ul> <li> Reviewed medical bills for the accuracy of the treatments, tests, and hospital stays prior to sanctioning the claims.</li> <li> Trained to interpret the codes (ICD-9, CPT) and terminology commonly used in medical billing to fully understand the paperwork that is submitted by healthcare providers.</li> <li> Required to have organizational and analytical skills as well as computer skills, knowledge of medical terminology and procedures, statistics, billing standards, data analysis and laws regarding medical billing.</li> </ul> </span> </div> </div> <div class="paragraph" id="PARAGRAPH_500375983_3_326506908" itemscope="" itemtype="https://schema.org/Organization" style="
      padding-top:15px;
    "> <div class="singlecolumn"> <span class="paddedline"> <span class="jobtitle" id="500375983JTIT3"> Assistant General Manager</span> <span> </span> <span class="datesWrapper"> <span class="jobdates" format="%b %Y" id="500375983JSTD3"> Jun 2010</span> <span>  to </span> <span class="jobdates" format="%b %Y" id="500375983EDDT3"> Dec 2010</span> <br/> </span> </span> <span class="paddedline" itemscope="" itemtype="https://schema.org/postalAddress"> <span class="companyname" id="500375983COMP3" itemprop="name"> Company Name</span> <span>  － </span> <span class="joblocation jobcity" id="500375983JCIT3" itemprop="addressLocality"> City</span> <span> , </span> <span class="joblocation jobstate" id="500375983JSTA3" itemprop="addressRegion"> State</span> </span> <span class="jobline" id="500375983JDES3" itemprop="description"> <ul> <li> Performed duties including but not limited to, budgeting and financial management, accounting, human resources, payroll and purchasing.</li> <li> Established and maintained close working relationships with all departments of the hotel to ensure maximum operation, productivity, morale and guest service.</li> <li> Handled daily operations and reported directly to the corporate office.</li> <li> Hired and trained staff on overall objectives and goals with an emphasis on high customer service.</li> <li> Marketing and Advertising, working on public relations with the media, government and local businesses and Chamber of Commerce.</li> </ul> </span> </div> </div> <div class="paragraph" id="PARAGRAPH_500375983_4_326506910" itemscope="" itemtype="https://schema.org/Organization" style="
      padding-top:5px;
    "> <div class="singlecolumn"> <span class="paddedline"> <span class="jobtitle" id="500375983JTIT4"> Executive Support / Marketing Assistant</span> <span> </span> <span class="datesWrapper"> <span class="jobdates" format="%b %Y" id="500375983JSTD4"> Jul 2007</span> <span>  to </span> <span class="jobdates" format="%b %Y" id="500375983EDDT4"> Jun 2010</span> <br/> </span> </span> <span class="paddedline" itemscope="" itemtype="https://schema.org/postalAddress"> <span class="companyname" id="500375983COMP4" itemprop="name"> Company Name</span> <span>  － </span> <span class="joblocation jobcity" id="500375983JCIT4" itemprop="addressLocality"> City</span> <span> , </span> <span class="joblocation jobstate" id="500375983JSTA4" itemprop="addressRegion"> State</span> </span> <span class="jobline" id="500375983JDES4" itemprop="description"> <ul> <li> Provided assistance to various department heads - Executive, Marketing, Customer Service, Human Resources.</li> <li> Managed front-end operations to ensure friendly and efficient transactions.</li> <li> Ensured the swift resolution of customer issues to preserve customer loyalty while complying with company policies.</li> <li> Exemplified the second-to-none customer service delivery in all interactions with customers and potential clients.</li> </ul> </span> </div> </div> <div class="paragraph" id="PARAGRAPH_500375983_5_326506911" itemscope="" itemtype="https://schema.org/Organization" style="
      padding-top:10px;
    "> <div class="singlecolumn"> <span class="paddedline"> <span class="jobtitle" id="500375983JTIT5"> Reservation &amp; Front Office Manager</span> <span> </span> <span class="datesWrapper"> <span class="jobdates" format="%b %Y" id="500375983JSTD5"> Jun 2004</span> <span>  to </span> <span class="jobdates" format="%b %Y" id="500375983EDDT5"> Jul 2007</span> <br/> </span> </span> <span class="paddedline" itemscope="" itemtype="https://schema.org/postalAddress"> <span class="companyname" id="500375983COMP5" itemprop="name"> Company Name</span> <span>  － </span> <span class="joblocation jobcity" id="500375983JCIT5" itemprop="addressLocality"> City</span> <span> , </span> <span class="joblocation jobstate" id="500375983JSTA5" itemprop="addressRegion"> State</span> </span> <span class="jobline" id="500375983JDES5" itemprop="description"> </span> </div> </div> <div class="paragraph" id="PARAGRAPH_500375983_6_326506912" itemscope="" itemtype="https://schema.org/Organization" style="
      padding-top:10px;
    "> <div class="singlecolumn"> <span class="paddedline"> <span class="jobtitle" id="500375983JTIT6"> Owner/ Partner</span> <span> </span> <span class="datesWrapper"> <span class="jobdates" format="%b %Y" id="500375983JSTD6"> Dec 2001</span> <span>  to </span> <span class="jobdates" format="%b %Y" id="500375983EDDT6"> May 2004</span> <br/> </span> </span> <span class="paddedline" itemscope="" itemtype="https://schema.org/postalAddress"> <span class="companyname" id="500375983COMP6" itemprop="name"> Company Name</span> <span>  － </span> <span class="joblocation jobcity" id="500375983JCIT6" itemprop="addressLocality"> City</span> <span> , </span> <span class="joblocation jobstate" id="500375983JSTA6" itemprop="addressRegion"> State</span> </span> <span class="jobline" id="500375983JDES6" itemprop="description"> </span> </div> </div> <div class="paragraph" id="PARAGRAPH_500375983_7_326506913" itemscope="" itemtype="https://schema.org/Organization" style="
      padding-top:10px;
    "> <div class="singlecolumn"> <span class="paddedline"> <span class="jobtitle" id="500375983JTIT7"> Price Integrity Coordinator</span> <span> </span> <span class="datesWrapper"> <span class="jobdates" format="%b %Y" id="500375983JSTD7"> Aug 1999</span> <span>  to </span> <span class="jobdates" format="%b %Y" id="500375983EDDT7"> Dec 2001</span> <br/> </span> </span> <span class="paddedline" itemscope="" itemtype="https://schema.org/postalAddress"> <span class="companyname" id="500375983COMP7" itemprop="name"> Company Name</span> <span>  － </span> <span class="joblocation jobcity" id="500375983JCIT7" itemprop="addressLocality"> City</span> <span> , </span> <span class="joblocation jobstate" id="500375983JSTA7" itemprop="addressRegion"> State</span> </span> <span class="jobline" id="500375983JDES7" itemprop="description"> </span> </div> </div> </div> <div class="section" id="SECTION_EDUC500400498" style="
      padding-top:0px;
    "> <div class="heading bottomborder"> <div class="sectiontitle" id="SECTNAME_EDUC500400498"> Education</div> </div> <div class="paragraph firstparagraph" id="PARAGRAPH_500400498_1_326523310" itemscope="" itemtype="https://schema.org/EducationalOrganization" style="
      padding-top:0px;
    "> <div class="singlecolumn"> <span class="paddedline" itemprop="description"> <span class="degree" id="500400498DGRE1" itemprop="name"> N/A</span> <span> , </span> <span class="programline" id="500400498STUY1"> Business Administration</span> <span class="datesWrapper"> <span class="jobdates" id="500400498GRYR1"> 1999</span> </span> </span> <span class="paddedline"> <span class="companyname companyname_educ" id="500400498SCHO1" itemprop="name"> Jefferson College</span> <span>  － </span> <span class="joblocation jobcity" id="500400498SCIT1"> City</span> <span> , </span> <span class="joblocation jobstate" id="500400498SSTA1"> State</span> <span class="joblocation jobstate" id="500400498SCNT1"> </span> </span> <span class="field" id="500400498FRFM1"> <ul> <li> Business Administration</li> <li> Marketing / Advertising</li> </ul> </span> </div> </div> <div class="paragraph" id="PARAGRAPH_500400498_2_326522471" itemscope="" itemtype="https://schema.org/EducationalOrganization" style="
      padding-top:0px;
    "> <div class="singlecolumn"> <span class="paddedline" itemprop="description"> <span class="degree" id="500400498DGRE2" itemprop="name"> High School Diploma</span> <span> , </span> <span class="programline" id="500400498STUY2"> College Prep. studies</span> <span class="datesWrapper"> <span class="jobdates" id="500400498GRYR2"> 1998</span> </span> </span> <span class="paddedline"> <span class="companyname companyname_educ" id="500400498SCHO2" itemprop="name"> Sainte Genevieve Senior High</span> <span>  － </span> <span class="joblocation jobcity" id="500400498SCIT2"> City</span> <span> , </span> <span class="joblocation jobstate" id="500400498SSTA2"> State</span> <span class="joblocation jobstate" id="500400498SCNT2"> </span> </span> <span class="field" id="500400498FRFM2"> <ul> <li> Awarded American Shrubel Leadership Scholarship to Jefferson College</li> </ul> </span> </div> </div> </div> <div class="section" id="SECTION_SKLL500375994" style="
      padding-top:0px;
    "> <div class="heading bottomborder"> <div class="sectiontitle" id="SECTNAME_SKLL500375994"> Skills</div> </div> <div class="paragraph firstparagraph" id="PARAGRAPH_500375994_1_326506918" style="
      padding-top:0px;
    "> <div class="field singlecolumn" id="500375994FRFM1"> <p align="LEFT"> Accounting, ads, advertising, analytical skills, benefits, billing, budgeting, clients, Customer Service, data analysis, delivery, documentation, employee relations, financial management, government relations, Human Resources, insurance, labor relations, layout, Marketing, marketing collateral, medical billing, medical terminology, office, organizational, payroll, performance reviews, personnel, policies, posters, presentations, public relations, purchasing, reporting, statistics, website.</p> </div> </div> </div> </div>

In [1]:
clean_df = df.copy()

NameError: name 'df' is not defined

In [2]:
print("Hello")

Hello

In [3]:
import pandas as pd
df = pd.read_csv("../data/resumes/Resume.csv")
df.head()

,ID,Resume_str,Resume_html,Category
0,16852973,HR ADMINISTRATOR/MARKETING ASSOCIATE\...,"<div class=""fontsize fontface vmargins hmargin...",HR
1,22323967,"HR SPECIALIST, US HR OPERATIONS ...","<div class=""fontsize fontface vmargins hmargin...",HR
2,33176873,HR DIRECTOR Summary Over 2...,"<div class=""fontsize fontface vmargins hmargin...",HR
3,27018550,HR SPECIALIST Summary Dedica...,"<div class=""fontsize fontface vmargins hmargin...",HR
4,17812897,HR MANAGER Skill Highlights ...,"<div class=""fontsize fontface vmargins hmargin...",HR

In [4]:
df.shape

(2484, 4)

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2484 entries, 0 to 2483
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ID           2484 non-null   int64
 1   Resume_str   2484 non-null   str
 2   Resume_html  2484 non-null   str
 3   Category     2484 non-null   str
dtypes: int64(1), str(3)
memory usage: 52.3 MB

In [6]:
df.isnull().sum()

ID             0
Resume_str     0
Resume_html    0
Category       0
dtype: int64

In [7]:
df["Category"].value_counts()

Category
INFORMATION-TECHNOLOGY    120
BUSINESS-DEVELOPMENT      120
ADVOCATE                  118
CHEF                      118
FINANCE                   118
ENGINEERING               118
ACCOUNTANT                118
FITNESS                   117
AVIATION                  117
SALES                     116
HEALTHCARE                115
CONSULTANT                115
BANKING                   115
CONSTRUCTION              112
PUBLIC-RELATIONS          111
HR                        110
DESIGNER                  107
ARTS                      103
TEACHER                   102
APPAREL                    97
DIGITAL-MEDIA              96
AGRICULTURE                63
AUTOMOBILE                 36
BPO                        22
Name: count, dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
print(df["Resume_str"].iloc[0])

         HR ADMINISTRATOR/MARKETING ASSOCIATE

HR ADMINISTRATOR       Summary     Dedicated Customer Service Manager with 15+ years of experience in Hospitality and Customer Service Management.   Respected builder and leader of customer-focused teams; strives to instill a shared, enthusiastic commitment to customer service.         Highlights         Focused on customer satisfaction  Team management  Marketing savvy  Conflict resolution techniques     Training and development  Skilled multi-tasker  Client relations specialist           Accomplishments      Missouri DOT Supervisor Training Certification  Certified by IHG in Customer Loyalty and Marketing by Segment   Hilton Worldwide General Manager Training Certification  Accomplished Trainer for cross server hospitality systems such as    Hilton OnQ  ,   Micros    Opera PMS   , Fidelio    OPERA    Reservation System (ORS) ,   Holidex    Completed courses and seminars in customer service, sales strategies, inventory control, loss prevention, safety, time management, leadership and performance assessment.        Experience      HR Administrator/Marketing Associate

HR Administrator     Dec 2013   to   Current      Company Name   －   City  ,   State     Helps to develop policies, directs and coordinates activities such as employment, compensation, labor relations, benefits, training, and employee services.  Prepares employee separation notices and related documentation  Keeps records of benefits plans participation such as insurance and pension plan, personnel transactions such as hires, promotions, transfers, performance reviews, and terminations, and employee statistics for government reporting.  Advises management in appropriate resolution of employee relations issues.  Administers benefits programs such as life, health, dental, insurance, pension plans, vacation, sick leave, leave of absence, and employee assistance.     Marketing Associate     Designed and created marketing collateral for sales meetings, trade shows and company executives.  Managed the in-house advertising program consisting of print and media collateral pieces.  Assisted in the complete design and launch of the company's website in 2 months.  Created an official company page on Facebook to facilitate interaction with customers.  Analyzed ratings and programming features of competitors to evaluate the effectiveness of marketing strategies.         Advanced Medical Claims Analyst     Mar 2012   to   Dec 2013      Company Name   －   City  ,   State     Reviewed medical bills for the accuracy of the treatments, tests, and hospital stays prior to sanctioning the claims.  Trained to interpret the codes (ICD-9, CPT) and terminology commonly used in medical billing to fully understand the paperwork that is submitted by healthcare providers.  Required to have organizational and analytical skills as well as computer skills, knowledge of medical terminology and procedures, statistics, billing standards, data analysis and laws regarding medical billing.         Assistant General Manager     Jun 2010   to   Dec 2010      Company Name   －   City  ,   State     Performed duties including but not limited to, budgeting and financial management, accounting, human resources, payroll and purchasing.  Established and maintained close working relationships with all departments of the hotel to ensure maximum operation, productivity, morale and guest service.  Handled daily operations and reported directly to the corporate office.  Hired and trained staff on overall objectives and goals with an emphasis on high customer service.  Marketing and Advertising, working on public relations with the media, government and local businesses and Chamber of Commerce.         Executive Support / Marketing Assistant     Jul 2007   to   Jun 2010      Company Name   －   City  ,   State     Provided assistance to various department heads - Executive, Marketing, Customer Service, Human Resources.  Managed front-end operations to ensure friendly and efficient transactions.  Ensured the swift resolution of customer issues to preserve customer loyalty while complying with company policies.  Exemplified the second-to-none customer service delivery in all interactions with customers and potential clients.         Reservation & Front Office Manager     Jun 2004   to   Jul 2007      Company Name   －   City  ,   State          Owner/ Partner     Dec 2001   to   May 2004      Company Name   －   City  ,   State          Price Integrity Coordinator     Aug 1999   to   Dec 2001      Company Name   －   City  ,   State          Education      N/A  ,   Business Administration   1999     Jefferson College   －   City  ,   State       Business Administration  Marketing / Advertising         High School Diploma  ,   College Prep. studies   1998     Sainte Genevieve Senior High   －   City  ,   State       Awarded American Shrubel Leadership Scholarship to Jefferson College         Skills     Accounting, ads, advertising, analytical skills, benefits, billing, budgeting, clients, Customer Service, data analysis, delivery, documentation, employee relations, financial management, government relations, Human Resources, insurance, labor relations, layout, Marketing, marketing collateral, medical billing, medical terminology, office, organizational, payroll, performance reviews, personnel, policies, posters, presentations, public relations, purchasing, reporting, statistics, website.

In [10]:
print(df["Resume_html"].iloc[0])

<div class="fontsize fontface vmargins hmargins linespacing pagesize" id="document"> <div class="section firstsection" id="SECTION_NAME500375979" style="
      padding-top:0px;
    "> <div class="paragraph PARAGRAPH_NAME firstparagraph" id="PARAGRAPH_500375979_1_326506904" style="
      padding-top:0px;
    "> <div class="name" itemprop="name"> <span class="field fName" id="500375979FNAM1"> </span> <span> </span> <span class="field" id="500375979LNAM1"> HR ADMINISTRATOR/MARKETING ASSOCIATE

HR ADMINISTRATOR</span> </div> </div> </div> <div class="section" id="SECTION_SUMM500375981" style="
      padding-top:0px;
    "> <div class="heading bottomborder"> <div class="sectiontitle" id="SECTNAME_SUMM500375981"> Summary</div> </div> <div class="paragraph firstparagraph" id="PARAGRAPH_500375981_1_326506917" style="
      padding-top:0px;
    "> <div class="field singlecolumn" id="500375981FRFM1"> <p align="LEFT"> Dedicated Customer Service Manager with 15+ years of experience in Hospitality and Customer Service Management. </p> <p align="LEFT"> Respected builder and leader of customer-focused teams; strives to instill a shared, enthusiastic commitment to customer service.  </p> </div> </div> </div> <div class="section" id="SECTION_HILT500375982" style="
      padding-top:0px;
    "> <div class="heading bottomborder"> <div class="sectiontitle" id="SECTNAME_HILT500375982"> Highlights</div> </div> <div class="paragraph firstparagraph" id="PARAGRAPH_500375982_1_326509244" style="
      padding-top:0px;
    "> <div class="singlecolumn maincolumn"> <table class="twocol"> <tbody> <tr> <td class="field twocol_1" id="500375982SKC11"> <p align="CENTER"> Focused on customer satisfaction</p> <p align="CENTER"> Team management</p> <p align="CENTER"> Marketing savvy</p> <p align="CENTER"> Conflict resolution techniques</p> <br/> </td> <td class="field twocol_2" id="500375982SKC21"> <p align="CENTER"> Training and development</p> <p align="CENTER"> Skilled multi-tasker</p> <p align="CENTER"> Client relations specialist</p> </td> </tr> </tbody> </table> </div> </div> </div> <div class="section" id="SECTION_ACCM500375993" style="
      padding-top:0px;
    "> <div class="heading bottomborder"> <div class="sectiontitle" id="SECTNAME_ACCM500375993"> Accomplishments</div> </div> <div class="paragraph firstparagraph" id="PARAGRAPH_500375993_1_326506914" style="
      padding-top:0px;
    "> <div class="field singlecolumn" id="500375993FRFM1"> <ul> <li> Missouri DOT Supervisor Training Certification</li> <li> Certified by IHG in Customer Loyalty and Marketing by Segment </li> <li> Hilton Worldwide General Manager Training Certification</li> <li> Accomplished Trainer for cross server hospitality systems such as  <b> <u> Hilton OnQ</u> </b> ,  <u> Micros </u> <b> <u> Opera PMS</u> </b> <u> , Fidelio </u> <b> <u> OPERA</u> </b> <u>  Reservation System (ORS)</u> , <b> <u> Holidex</u> </b> </li> <li> Completed courses and seminars in customer service, sales strategies, inventory control, loss prevention, safety, time management, leadership and performance assessment.</li> </ul> </div> </div> </div> <div class="section" id="SECTION_EXPR500375983" style="
      padding-top:0px;
    "> <div class="heading bottomborder"> <div class="sectiontitle" id="SECTNAME_EXPR500375983"> Experience</div> </div> <div class="paragraph firstparagraph" id="PARAGRAPH_500375983_1_326506906" itemscope="" itemtype="https://schema.org/Organization" style="
      padding-top:0px;
    "> <div class="singlecolumn"> <span class="paddedline"> <span class="jobtitle" id="500375983JTIT1"> HR Administrator/Marketing Associate

HR Administrator</span> <span> </span> <span class="datesWrapper"> <span class="jobdates" format="%b %Y" id="500375983JSTD1"> Dec 2013</span> <span>  to </span> <span class="jobdates" format="%b %Y" id="500375983EDDT1"> Current</span> <br/> </span> </span> <span class="paddedline" itemscope="" itemtype="https://schema.org/postalAddress"> <span class="companyname" id="500375983COMP1" itemprop="name"> Company Name</span> <span>  － </span> <span class="joblocation jobcity" id="500375983JCIT1" itemprop="addressLocality"> City</span> <span> , </span> <span class="joblocation jobstate" id="500375983JSTA1" itemprop="addressRegion"> State</span> </span> <span class="jobline" id="500375983JDES1" itemprop="description"> <ul> <li> Helps to develop policies, directs and coordinates activities such as employment, compensation, labor relations, benefits, training, and employee services.</li> <li> Prepares employee separation notices and related documentation</li> <li> Keeps records of benefits plans participation such as insurance and pension plan, personnel transactions such as hires, promotions, transfers, performance reviews, and terminations, and employee statistics for government reporting.</li> <li> Advises management in appropriate resolution of employee relations issues.</li> <li> Administers benefits programs such as life, health, dental, insurance, pension plans, vacation, sick leave, leave of absence, and employee assistance.</li> </ul> <br/> <p align="LEFT"> <b> Marketing Associate</b>  </p> <ul> <li> Designed and created marketing collateral for sales meetings, trade shows and company executives.</li> <li> Managed the in-house advertising program consisting of print and media collateral pieces.</li> <li> Assisted in the complete design and launch of the company's website in 2 months.</li> <li> Created an official company page on Facebook to facilitate interaction with customers.</li> <li> Analyzed ratings and programming features of competitors to evaluate the effectiveness of marketing strategies.</li> </ul> </span> </div> </div> <div class="paragraph" id="PARAGRAPH_500375983_2_326506907" itemscope="" itemtype="https://schema.org/Organization" style="
      padding-top:10px;
    "> <div class="singlecolumn"> <span class="paddedline"> <span class="jobtitle" id="500375983JTIT2"> Advanced Medical Claims Analyst</span> <span> </span> <span class="datesWrapper"> <span class="jobdates" format="%b %Y" id="500375983JSTD2"> Mar 2012</span> <span>  to </span> <span class="jobdates" format="%b %Y" id="500375983EDDT2"> Dec 2013</span> <br/> </span> </span> <span class="paddedline" itemscope="" itemtype="https://schema.org/postalAddress"> <span class="companyname" id="500375983COMP2" itemprop="name"> Company Name</span> <span>  － </span> <span class="joblocation jobcity" id="500375983JCIT2" itemprop="addressLocality"> City</span> <span> , </span> <span class="joblocation jobstate" id="500375983JSTA2" itemprop="addressRegion"> State</span> </span> <span class="jobline" id="500375983JDES2" itemprop="description"> <ul> <li> Reviewed medical bills for the accuracy of the treatments, tests, and hospital stays prior to sanctioning the claims.</li> <li> Trained to interpret the codes (ICD-9, CPT) and terminology commonly used in medical billing to fully understand the paperwork that is submitted by healthcare providers.</li> <li> Required to have organizational and analytical skills as well as computer skills, knowledge of medical terminology and procedures, statistics, billing standards, data analysis and laws regarding medical billing.</li> </ul> </span> </div> </div> <div class="paragraph" id="PARAGRAPH_500375983_3_326506908" itemscope="" itemtype="https://schema.org/Organization" style="
      padding-top:15px;
    "> <div class="singlecolumn"> <span class="paddedline"> <span class="jobtitle" id="500375983JTIT3"> Assistant General Manager</span> <span> </span> <span class="datesWrapper"> <span class="jobdates" format="%b %Y" id="500375983JSTD3"> Jun 2010</span> <span>  to </span> <span class="jobdates" format="%b %Y" id="500375983EDDT3"> Dec 2010</span> <br/> </span> </span> <span class="paddedline" itemscope="" itemtype="https://schema.org/postalAddress"> <span class="companyname" id="500375983COMP3" itemprop="name"> Company Name</span> <span>  － </span> <span class="joblocation jobcity" id="500375983JCIT3" itemprop="addressLocality"> City</span> <span> , </span> <span class="joblocation jobstate" id="500375983JSTA3" itemprop="addressRegion"> State</span> </span> <span class="jobline" id="500375983JDES3" itemprop="description"> <ul> <li> Performed duties including but not limited to, budgeting and financial management, accounting, human resources, payroll and purchasing.</li> <li> Established and maintained close working relationships with all departments of the hotel to ensure maximum operation, productivity, morale and guest service.</li> <li> Handled daily operations and reported directly to the corporate office.</li> <li> Hired and trained staff on overall objectives and goals with an emphasis on high customer service.</li> <li> Marketing and Advertising, working on public relations with the media, government and local businesses and Chamber of Commerce.</li> </ul> </span> </div> </div> <div class="paragraph" id="PARAGRAPH_500375983_4_326506910" itemscope="" itemtype="https://schema.org/Organization" style="
      padding-top:5px;
    "> <div class="singlecolumn"> <span class="paddedline"> <span class="jobtitle" id="500375983JTIT4"> Executive Support / Marketing Assistant</span> <span> </span> <span class="datesWrapper"> <span class="jobdates" format="%b %Y" id="500375983JSTD4"> Jul 2007</span> <span>  to </span> <span class="jobdates" format="%b %Y" id="500375983EDDT4"> Jun 2010</span> <br/> </span> </span> <span class="paddedline" itemscope="" itemtype="https://schema.org/postalAddress"> <span class="companyname" id="500375983COMP4" itemprop="name"> Company Name</span> <span>  － </span> <span class="joblocation jobcity" id="500375983JCIT4" itemprop="addressLocality"> City</span> <span> , </span> <span class="joblocation jobstate" id="500375983JSTA4" itemprop="addressRegion"> State</span> </span> <span class="jobline" id="500375983JDES4" itemprop="description"> <ul> <li> Provided assistance to various department heads - Executive, Marketing, Customer Service, Human Resources.</li> <li> Managed front-end operations to ensure friendly and efficient transactions.</li> <li> Ensured the swift resolution of customer issues to preserve customer loyalty while complying with company policies.</li> <li> Exemplified the second-to-none customer service delivery in all interactions with customers and potential clients.</li> </ul> </span> </div> </div> <div class="paragraph" id="PARAGRAPH_500375983_5_326506911" itemscope="" itemtype="https://schema.org/Organization" style="
      padding-top:10px;
    "> <div class="singlecolumn"> <span class="paddedline"> <span class="jobtitle" id="500375983JTIT5"> Reservation &amp; Front Office Manager</span> <span> </span> <span class="datesWrapper"> <span class="jobdates" format="%b %Y" id="500375983JSTD5"> Jun 2004</span> <span>  to </span> <span class="jobdates" format="%b %Y" id="500375983EDDT5"> Jul 2007</span> <br/> </span> </span> <span class="paddedline" itemscope="" itemtype="https://schema.org/postalAddress"> <span class="companyname" id="500375983COMP5" itemprop="name"> Company Name</span> <span>  － </span> <span class="joblocation jobcity" id="500375983JCIT5" itemprop="addressLocality"> City</span> <span> , </span> <span class="joblocation jobstate" id="500375983JSTA5" itemprop="addressRegion"> State</span> </span> <span class="jobline" id="500375983JDES5" itemprop="description"> </span> </div> </div> <div class="paragraph" id="PARAGRAPH_500375983_6_326506912" itemscope="" itemtype="https://schema.org/Organization" style="
      padding-top:10px;
    "> <div class="singlecolumn"> <span class="paddedline"> <span class="jobtitle" id="500375983JTIT6"> Owner/ Partner</span> <span> </span> <span class="datesWrapper"> <span class="jobdates" format="%b %Y" id="500375983JSTD6"> Dec 2001</span> <span>  to </span> <span class="jobdates" format="%b %Y" id="500375983EDDT6"> May 2004</span> <br/> </span> </span> <span class="paddedline" itemscope="" itemtype="https://schema.org/postalAddress"> <span class="companyname" id="500375983COMP6" itemprop="name"> Company Name</span> <span>  － </span> <span class="joblocation jobcity" id="500375983JCIT6" itemprop="addressLocality"> City</span> <span> , </span> <span class="joblocation jobstate" id="500375983JSTA6" itemprop="addressRegion"> State</span> </span> <span class="jobline" id="500375983JDES6" itemprop="description"> </span> </div> </div> <div class="paragraph" id="PARAGRAPH_500375983_7_326506913" itemscope="" itemtype="https://schema.org/Organization" style="
      padding-top:10px;
    "> <div class="singlecolumn"> <span class="paddedline"> <span class="jobtitle" id="500375983JTIT7"> Price Integrity Coordinator</span> <span> </span> <span class="datesWrapper"> <span class="jobdates" format="%b %Y" id="500375983JSTD7"> Aug 1999</span> <span>  to </span> <span class="jobdates" format="%b %Y" id="500375983EDDT7"> Dec 2001</span> <br/> </span> </span> <span class="paddedline" itemscope="" itemtype="https://schema.org/postalAddress"> <span class="companyname" id="500375983COMP7" itemprop="name"> Company Name</span> <span>  － </span> <span class="joblocation jobcity" id="500375983JCIT7" itemprop="addressLocality"> City</span> <span> , </span> <span class="joblocation jobstate" id="500375983JSTA7" itemprop="addressRegion"> State</span> </span> <span class="jobline" id="500375983JDES7" itemprop="description"> </span> </div> </div> </div> <div class="section" id="SECTION_EDUC500400498" style="
      padding-top:0px;
    "> <div class="heading bottomborder"> <div class="sectiontitle" id="SECTNAME_EDUC500400498"> Education</div> </div> <div class="paragraph firstparagraph" id="PARAGRAPH_500400498_1_326523310" itemscope="" itemtype="https://schema.org/EducationalOrganization" style="
      padding-top:0px;
    "> <div class="singlecolumn"> <span class="paddedline" itemprop="description"> <span class="degree" id="500400498DGRE1" itemprop="name"> N/A</span> <span> , </span> <span class="programline" id="500400498STUY1"> Business Administration</span> <span class="datesWrapper"> <span class="jobdates" id="500400498GRYR1"> 1999</span> </span> </span> <span class="paddedline"> <span class="companyname companyname_educ" id="500400498SCHO1" itemprop="name"> Jefferson College</span> <span>  － </span> <span class="joblocation jobcity" id="500400498SCIT1"> City</span> <span> , </span> <span class="joblocation jobstate" id="500400498SSTA1"> State</span> <span class="joblocation jobstate" id="500400498SCNT1"> </span> </span> <span class="field" id="500400498FRFM1"> <ul> <li> Business Administration</li> <li> Marketing / Advertising</li> </ul> </span> </div> </div> <div class="paragraph" id="PARAGRAPH_500400498_2_326522471" itemscope="" itemtype="https://schema.org/EducationalOrganization" style="
      padding-top:0px;
    "> <div class="singlecolumn"> <span class="paddedline" itemprop="description"> <span class="degree" id="500400498DGRE2" itemprop="name"> High School Diploma</span> <span> , </span> <span class="programline" id="500400498STUY2"> College Prep. studies</span> <span class="datesWrapper"> <span class="jobdates" id="500400498GRYR2"> 1998</span> </span> </span> <span class="paddedline"> <span class="companyname companyname_educ" id="500400498SCHO2" itemprop="name"> Sainte Genevieve Senior High</span> <span>  － </span> <span class="joblocation jobcity" id="500400498SCIT2"> City</span> <span> , </span> <span class="joblocation jobstate" id="500400498SSTA2"> State</span> <span class="joblocation jobstate" id="500400498SCNT2"> </span> </span> <span class="field" id="500400498FRFM2"> <ul> <li> Awarded American Shrubel Leadership Scholarship to Jefferson College</li> </ul> </span> </div> </div> </div> <div class="section" id="SECTION_SKLL500375994" style="
      padding-top:0px;
    "> <div class="heading bottomborder"> <div class="sectiontitle" id="SECTNAME_SKLL500375994"> Skills</div> </div> <div class="paragraph firstparagraph" id="PARAGRAPH_500375994_1_326506918" style="
      padding-top:0px;
    "> <div class="field singlecolumn" id="500375994FRFM1"> <p align="LEFT"> Accounting, ads, advertising, analytical skills, benefits, billing, budgeting, clients, Customer Service, data analysis, delivery, documentation, employee relations, financial management, government relations, Human Resources, insurance, labor relations, layout, Marketing, marketing collateral, medical billing, medical terminology, office, organizational, payroll, performance reviews, personnel, policies, posters, presentations, public relations, purchasing, reporting, statistics, website.</p> </div> </div> </div> </div>

In [11]:
clean_df = df.copy()

In [12]:
clean_df.head()

,ID,Resume_str,Resume_html,Category
0,16852973,HR ADMINISTRATOR/MARKETING ASSOCIATE\...,"<div class=""fontsize fontface vmargins hmargin...",HR
1,22323967,"HR SPECIALIST, US HR OPERATIONS ...","<div class=""fontsize fontface vmargins hmargin...",HR
2,33176873,HR DIRECTOR Summary Over 2...,"<div class=""fontsize fontface vmargins hmargin...",HR
3,27018550,HR SPECIALIST Summary Dedica...,"<div class=""fontsize fontface vmargins hmargin...",HR
4,17812897,HR MANAGER Skill Highlights ...,"<div class=""fontsize fontface vmargins hmargin...",HR

In [13]:
clean_df = clean_df.drop(columns=["Resume_html"])

In [14]:
clean_df.head()

         ID                                         Resume_str Category
0  16852973           HR ADMINISTRATOR/MARKETING ASSOCIATE\...       HR
1  22323967           HR SPECIALIST, US HR OPERATIONS      ...       HR
2  33176873           HR DIRECTOR       Summary      Over 2...       HR
3  27018550           HR SPECIALIST       Summary    Dedica...       HR
4  17812897           HR MANAGER         Skill Highlights  ...       HR

In [15]:
clean_df.columns

Index(['ID', 'Resume_str', 'Category'], dtype='str')

In [16]:
clean_df = clean_df.rename(columns={
    "Resume_str": "resume_text"
})

In [17]:
clean_df.columns

Index(['ID', 'resume_text', 'Category'], dtype='str')

In [18]:
print(clean_df["resume_text"].iloc[0])

         HR ADMINISTRATOR/MARKETING ASSOCIATE

HR ADMINISTRATOR       Summary     Dedicated Customer Service Manager with 15+ years of experience in Hospitality and Customer Service Management.   Respected builder and leader of customer-focused teams; strives to instill a shared, enthusiastic commitment to customer service.         Highlights         Focused on customer satisfaction  Team management  Marketing savvy  Conflict resolution techniques     Training and development  Skilled multi-tasker  Client relations specialist           Accomplishments      Missouri DOT Supervisor Training Certification  Certified by IHG in Customer Loyalty and Marketing by Segment   Hilton Worldwide General Manager Training Certification  Accomplished Trainer for cross server hospitality systems such as    Hilton OnQ  ,   Micros    Opera PMS   , Fidelio    OPERA    Reservation System (ORS) ,   Holidex    Completed courses and seminars in customer service, sales strategies, inventory control, loss prevention, safety, time management, leadership and performance assessment.        Experience      HR Administrator/Marketing Associate

HR Administrator     Dec 2013   to   Current      Company Name   －   City  ,   State     Helps to develop policies, directs and coordinates activities such as employment, compensation, labor relations, benefits, training, and employee services.  Prepares employee separation notices and related documentation  Keeps records of benefits plans participation such as insurance and pension plan, personnel transactions such as hires, promotions, transfers, performance reviews, and terminations, and employee statistics for government reporting.  Advises management in appropriate resolution of employee relations issues.  Administers benefits programs such as life, health, dental, insurance, pension plans, vacation, sick leave, leave of absence, and employee assistance.     Marketing Associate     Designed and created marketing collateral for sales meetings, trade shows and company executives.  Managed the in-house advertising program consisting of print and media collateral pieces.  Assisted in the complete design and launch of the company's website in 2 months.  Created an official company page on Facebook to facilitate interaction with customers.  Analyzed ratings and programming features of competitors to evaluate the effectiveness of marketing strategies.         Advanced Medical Claims Analyst     Mar 2012   to   Dec 2013      Company Name   －   City  ,   State     Reviewed medical bills for the accuracy of the treatments, tests, and hospital stays prior to sanctioning the claims.  Trained to interpret the codes (ICD-9, CPT) and terminology commonly used in medical billing to fully understand the paperwork that is submitted by healthcare providers.  Required to have organizational and analytical skills as well as computer skills, knowledge of medical terminology and procedures, statistics, billing standards, data analysis and laws regarding medical billing.         Assistant General Manager     Jun 2010   to   Dec 2010      Company Name   －   City  ,   State     Performed duties including but not limited to, budgeting and financial management, accounting, human resources, payroll and purchasing.  Established and maintained close working relationships with all departments of the hotel to ensure maximum operation, productivity, morale and guest service.  Handled daily operations and reported directly to the corporate office.  Hired and trained staff on overall objectives and goals with an emphasis on high customer service.  Marketing and Advertising, working on public relations with the media, government and local businesses and Chamber of Commerce.         Executive Support / Marketing Assistant     Jul 2007   to   Jun 2010      Company Name   －   City  ,   State     Provided assistance to various department heads - Executive, Marketing, Customer Service, Human Resources.  Managed front-end operations to ensure friendly and efficient transactions.  Ensured the swift resolution of customer issues to preserve customer loyalty while complying with company policies.  Exemplified the second-to-none customer service delivery in all interactions with customers and potential clients.         Reservation & Front Office Manager     Jun 2004   to   Jul 2007      Company Name   －   City  ,   State          Owner/ Partner     Dec 2001   to   May 2004      Company Name   －   City  ,   State          Price Integrity Coordinator     Aug 1999   to   Dec 2001      Company Name   －   City  ,   State          Education      N/A  ,   Business Administration   1999     Jefferson College   －   City  ,   State       Business Administration  Marketing / Advertising         High School Diploma  ,   College Prep. studies   1998     Sainte Genevieve Senior High   －   City  ,   State       Awarded American Shrubel Leadership Scholarship to Jefferson College         Skills     Accounting, ads, advertising, analytical skills, benefits, billing, budgeting, clients, Customer Service, data analysis, delivery, documentation, employee relations, financial management, government relations, Human Resources, insurance, labor relations, layout, Marketing, marketing collateral, medical billing, medical terminology, office, organizational, payroll, performance reviews, personnel, policies, posters, presentations, public relations, purchasing, reporting, statistics, website.

In [19]:
clean_df["resume_text"].isnull().sum()

np.int64(0)

In [20]:
import re

In [21]:
def clean_text(text):
    text = text.lower()
    text = re.sub(r'\s+', ' ', text)
    text = re.sub(r'[^a-zA-Z0-9\s]', ' ', text)
    text = text.strip()
    return text

In [22]:
clean_df["clean_resume"] = clean_df["resume_text"].apply(clean_text)

In [23]:
print("ORIGINAL:")
print(clean_df["resume_text"].iloc[0])

print("\nCLEANED:")
print(clean_df["clean_resume"].iloc[0])

ORIGINAL:
         HR ADMINISTRATOR/MARKETING ASSOCIATE

HR ADMINISTRATOR       Summary     Dedicated Customer Service Manager with 15+ years of experience in Hospitality and Customer Service Management.   Respected builder and leader of customer-focused teams; strives to instill a shared, enthusiastic commitment to customer service.         Highlights         Focused on customer satisfaction  Team management  Marketing savvy  Conflict resolution techniques     Training and development  Skilled multi-tasker  Client relations specialist           Accomplishments      Missouri DOT Supervisor Training Certification  Certified by IHG in Customer Loyalty and Marketing by Segment   Hilton Worldwide General Manager Training Certification  Accomplished Trainer for cross server hospitality systems such as    Hilton OnQ  ,   Micros    Opera PMS   , Fidelio    OPERA    Reservation System (ORS) ,   Holidex    Completed courses and seminars in customer service, sales strategies, inventory control, loss prevention, safety, time management, leadership and performance assessment.        Experience      HR Administrator/Marketing Associate

HR Administrator     Dec 2013   to   Current      Company Name   －   City  ,   State     Helps to develop policies, directs and coordinates activities such as employment, compensation, labor relations, benefits, training, and employee services.  Prepares employee separation notices and related documentation  Keeps records of benefits plans participation such as insurance and pension plan, personnel transactions such as hires, promotions, transfers, performance reviews, and terminations, and employee statistics for government reporting.  Advises management in appropriate resolution of employee relations issues.  Administers benefits programs such as life, health, dental, insurance, pension plans, vacation, sick leave, leave of absence, and employee assistance.     Marketing Associate     Designed and created marketing collateral for sales meetings, trade shows and company executives.  Managed the in-house advertising program consisting of print and media collateral pieces.  Assisted in the complete design and launch of the company's website in 2 months.  Created an official company page on Facebook to facilitate interaction with customers.  Analyzed ratings and programming features of competitors to evaluate the effectiveness of marketing strategies.         Advanced Medical Claims Analyst     Mar 2012   to   Dec 2013      Company Name   －   City  ,   State     Reviewed medical bills for the accuracy of the treatments, tests, and hospital stays prior to sanctioning the claims.  Trained to interpret the codes (ICD-9, CPT) and terminology commonly used in medical billing to fully understand the paperwork that is submitted by healthcare providers.  Required to have organizational and analytical skills as well as computer skills, knowledge of medical terminology and procedures, statistics, billing standards, data analysis and laws regarding medical billing.         Assistant General Manager     Jun 2010   to   Dec 2010      Company Name   －   City  ,   State     Performed duties including but not limited to, budgeting and financial management, accounting, human resources, payroll and purchasing.  Established and maintained close working relationships with all departments of the hotel to ensure maximum operation, productivity, morale and guest service.  Handled daily operations and reported directly to the corporate office.  Hired and trained staff on overall objectives and goals with an emphasis on high customer service.  Marketing and Advertising, working on public relations with the media, government and local businesses and Chamber of Commerce.         Executive Support / Marketing Assistant     Jul 2007   to   Jun 2010      Company Name   －   City  ,   State     Provided assistance to various department heads - Executive, Marketing, Customer Service, Human Resources.  Managed front-end operations to ensure friendly and efficient transactions.  Ensured the swift resolution of customer issues to preserve customer loyalty while complying with company policies.  Exemplified the second-to-none customer service delivery in all interactions with customers and potential clients.         Reservation & Front Office Manager     Jun 2004   to   Jul 2007      Company Name   －   City  ,   State          Owner/ Partner     Dec 2001   to   May 2004      Company Name   －   City  ,   State          Price Integrity Coordinator     Aug 1999   to   Dec 2001      Company Name   －   City  ,   State          Education      N/A  ,   Business Administration   1999     Jefferson College   －   City  ,   State       Business Administration  Marketing / Advertising         High School Diploma  ,   College Prep. studies   1998     Sainte Genevieve Senior High   －   City  ,   State       Awarded American Shrubel Leadership Scholarship to Jefferson College         Skills     Accounting, ads, advertising, analytical skills, benefits, billing, budgeting, clients, Customer Service, data analysis, delivery, documentation, employee relations, financial management, government relations, Human Resources, insurance, labor relations, layout, Marketing, marketing collateral, medical billing, medical terminology, office, organizational, payroll, performance reviews, personnel, policies, posters, presentations, public relations, purchasing, reporting, statistics, website.

CLEANED:
hr administrator marketing associate hr administrator summary dedicated customer service manager with 15  years of experience in hospitality and customer service management  respected builder and leader of customer focused teams  strives to instill a shared  enthusiastic commitment to customer service  highlights focused on customer satisfaction team management marketing savvy conflict resolution techniques training and development skilled multi tasker client relations specialist accomplishments missouri dot supervisor training certification certified by ihg in customer loyalty and marketing by segment hilton worldwide general manager training certification accomplished trainer for cross server hospitality systems such as hilton onq   micros opera pms   fidelio opera reservation system  ors    holidex completed courses and seminars in customer service  sales strategies  inventory control  loss prevention  safety  time management  leadership and performance assessment  experience hr administrator marketing associate hr administrator dec 2013 to current company name   city   state helps to develop policies  directs and coordinates activities such as employment  compensation  labor relations  benefits  training  and employee services  prepares employee separation notices and related documentation keeps records of benefits plans participation such as insurance and pension plan  personnel transactions such as hires  promotions  transfers  performance reviews  and terminations  and employee statistics for government reporting  advises management in appropriate resolution of employee relations issues  administers benefits programs such as life  health  dental  insurance  pension plans  vacation  sick leave  leave of absence  and employee assistance  marketing associate designed and created marketing collateral for sales meetings  trade shows and company executives  managed the in house advertising program consisting of print and media collateral pieces  assisted in the complete design and launch of the company s website in 2 months  created an official company page on facebook to facilitate interaction with customers  analyzed ratings and programming features of competitors to evaluate the effectiveness of marketing strategies  advanced medical claims analyst mar 2012 to dec 2013 company name   city   state reviewed medical bills for the accuracy of the treatments  tests  and hospital stays prior to sanctioning the claims  trained to interpret the codes  icd 9  cpt  and terminology commonly used in medical billing to fully understand the paperwork that is submitted by healthcare providers  required to have organizational and analytical skills as well as computer skills  knowledge of medical terminology and procedures  statistics  billing standards  data analysis and laws regarding medical billing  assistant general manager jun 2010 to dec 2010 company name   city   state performed duties including but not limited to  budgeting and financial management  accounting  human resources  payroll and purchasing  established and maintained close working relationships with all departments of the hotel to ensure maximum operation  productivity  morale and guest service  handled daily operations and reported directly to the corporate office  hired and trained staff on overall objectives and goals with an emphasis on high customer service  marketing and advertising  working on public relations with the media  government and local businesses and chamber of commerce  executive support   marketing assistant jul 2007 to jun 2010 company name   city   state provided assistance to various department heads   executive  marketing  customer service  human resources  managed front end operations to ensure friendly and efficient transactions  ensured the swift resolution of customer issues to preserve customer loyalty while complying with company policies  exemplified the second to none customer service delivery in all interactions with customers and potential clients  reservation   front office manager jun 2004 to jul 2007 company name   city   state owner  partner dec 2001 to may 2004 company name   city   state price integrity coordinator aug 1999 to dec 2001 company name   city   state education n a   business administration 1999 jefferson college   city   state business administration marketing   advertising high school diploma   college prep  studies 1998 sainte genevieve senior high   city   state awarded american shrubel leadership scholarship to jefferson college skills accounting  ads  advertising  analytical skills  benefits  billing  budgeting  clients  customer service  data analysis  delivery  documentation  employee relations  financial management  government relations  human resources  insurance  labor relations  layout  marketing  marketing collateral  medical billing  medical terminology  office  organizational  payroll  performance reviews  personnel  policies  posters  presentations  public relations  purchasing  reporting  statistics  website

In [24]:
clean_df["text_length"] = clean_df["clean_resume"].str.len()

In [25]:
clean_df["text_length"].describe()

count     2484.000000
mean      5925.843398
std       2685.124870
min          0.000000
25%       4813.750000
50%       5542.500000
75%       6844.250000
max      35216.000000
Name: text_length, dtype: float64

In [26]:
clean_df[clean_df["text_length"] == 0]

,ID,resume_text,Category,clean_resume,text_length
656,12632728,,BUSINESS-DEVELOPMENT,,0

In [27]:
(clean_df["text_length"] == 0).sum()

np.int64(1)

In [28]:
clean_df.loc[
    clean_df["text_length"] == 0,
    ["ID", "resume_text", "Category"]
]

           ID            resume_text              Category
656  12632728                         BUSINESS-DEVELOPMENT

In [29]:
clean_df = clean_df[clean_df["text_length"] > 0]

In [30]:
clean_df.shape

(2483, 5)

In [31]:
(clean_df["text_length"] == 0).sum()

np.int64(0)

In [32]:
clean_df.isnull().sum()

ID              0
resume_text     0
Category        0
clean_resume    0
text_length     0
dtype: int64

In [33]:
clean_df = clean_df.reset_index(drop=True)

In [34]:
clean_df.head()

,ID,resume_text,Category,clean_resume,text_length
0,16852973,HR ADMINISTRATOR/MARKETING ASSOCIATE\...,HR,hr administrator marketing associate hr admini...,5026
1,22323967,"HR SPECIALIST, US HR OPERATIONS ...",HR,hr specialist us hr operations summary versat...,5173
2,33176873,HR DIRECTOR Summary Over 2...,HR,hr director summary over 20 years experience i...,7340
3,27018550,HR SPECIALIST Summary Dedica...,HR,hr specialist summary dedicated driven and d...,2651
4,17812897,HR MANAGER Skill Highlights ...,HR,hr manager skill highlights hr skills hr depar...,8885

In [35]:
clean_df["clean_resume"].duplicated().sum()

np.int64(2)

In [36]:
clean_df[clean_df["clean_resume"].duplicated(keep=False)].sort_values("clean_resume")

,ID,resume_text,Category,clean_resume,text_length
1489,19147603,FINANCE OFFICER Professional ...,FINANCE,finance officer professional summary to attain...,4680
1508,28398216,FINANCE OFFICER Professional ...,FINANCE,finance officer professional summary to attain...,4680
2443,16850314,STOREKEEPER II Professional Sum...,AVIATION,storekeeper ii professional summary the purpos...,4978
2482,37473139,STOREKEEPER II Professional Sum...,AVIATION,storekeeper ii professional summary the purpos...,4978

In [37]:
clean_df = clean_df.drop_duplicates(
    subset=["clean_resume"],
    keep="first"
)

In [38]:
clean_df = clean_df.reset_index(drop=True)

In [39]:
clean_df.shape

(2481, 5)

In [40]:
clean_df["clean_resume"].duplicated().sum()

np.int64(0)

In [41]:
clean_df["text_length"].describe()

count     2481.000000
mean      5929.116082
std       2683.926016
min        688.000000
25%       4815.000000
50%       5543.000000
75%       6845.000000
max      35216.000000
Name: text_length, dtype: float64

In [42]:
clean_df.sort_values("text_length").head(10)

,ID,resume_text,Category,clean_resume,text_length
1929,22965804,CONSTRUCTION WORKER Highlig...,CONSTRUCTION,construction worker highlights highly motivate...,688
130,21705160,GRAPHIC DESIGNER Expe...,DESIGNER,graphic designer experience graphic designer j...,794
1048,12696104,SALES ASSOCIATE Summary Moti...,SALES,sales associate summary motivated sales associ...,838
1101,14381464,SALES ASSOCIATE Summary My g...,SALES,sales associate summary my goal is to become a...,843
153,78149576,FLORAL DESIGNER Skills B...,DESIGNER,floral designer skills billings cash handling...,900
1399,35468363,SUSHI CHEF Executive Profile ...,CHEF,sushi chef executive profile 14 years experien...,980
1850,24799301,ACCOUNTANT Summary Accountan...,ACCOUNTANT,accountant summary accountant for a medium siz...,1021
1038,98108571,SALES ASSOCIATE Experience ...,SALES,sales associate experience 04 2016 to current ...,1032
2320,30594821,CERTIFIED CUSTOM FRAMER Q...,ARTS,certified custom framer qualifications ability...,1113
1393,47317494,ASSISTANT CHEF Highlights ...,CHEF,assistant chef highlights microsoft word exce...,1122

In [43]:
clean_df[clean_df["text_length"] < 100]

Empty DataFrame
Columns: [ID, resume_text, Category, clean_resume, text_length]
Index: []

In [44]:
clean_df["text_length"].lt(100).sum()

np.int64(0)

In [45]:
clean_df["Category"].nunique()

24

In [46]:
clean_df["Category"].value_counts()

Category
INFORMATION-TECHNOLOGY    120
BUSINESS-DEVELOPMENT      119
ADVOCATE                  118
CHEF                      118
ENGINEERING               118
ACCOUNTANT                118
FITNESS                   117
FINANCE                   117
SALES                     116
AVIATION                  116
HEALTHCARE                115
CONSULTANT                115
BANKING                   115
CONSTRUCTION              112
PUBLIC-RELATIONS          111
HR                        110
DESIGNER                  107
ARTS                      103
TEACHER                   102
APPAREL                    97
DIGITAL-MEDIA              96
AGRICULTURE                63
AUTOMOBILE                 36
BPO                        22
Name: count, dtype: int64

In [47]:
clean_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2481 entries, 0 to 2480
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ID            2481 non-null   int64
 1   resume_text   2481 non-null   str
 2   Category      2481 non-null   str
 3   clean_resume  2481 non-null   str
 4   text_length   2481 non-null   int64
dtypes: int64(2), str(3)
memory usage: 29.1 MB

In [48]:
clean_df.isnull().sum()

ID              0
resume_text     0
Category        0
clean_resume    0
text_length     0
dtype: int64

In [49]:
clean_df.to_csv(
    "../data/processed/cleaned_resume.csv",
    index=False
)

In [50]:
import os

os.path.exists("../data/processed/cleaned_resume.csv")

True