In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data/processed/processed_resume.csv")

In [3]:
df.shape

(2481, 6)

In [4]:
df[["Category", "processed_resume"]].head()

  Category                                   processed_resume
0       HR  hr administrator marketing associate hr admini...
1       HR  hr specialist us hr operations summary versati...
2       HR  hr director summary 20 years experience recrui...
3       HR  hr specialist summary dedicated driven dynamic...
4       HR  hr manager skill highlights hr skills hr depar...

In [5]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [6]:
vectorizer = TfidfVectorizer()

In [7]:
tfidf_matrix = vectorizer.fit_transform(df["processed_resume"])

In [8]:
tfidf_matrix.shape

(2481, 40311)

In [9]:
feature_names = vectorizer.get_feature_names_out()

In [10]:
feature_names[:50]

array(['00', '000', '0001', '00019', '000401', '000k', '000mdthd',
       '000sq', '000sqft', '001', '00100', '0017', '0018', '002', '0028',
       '0029', '00296190', '003', '0031', '00313355', '0032', '0039',
       '004', '0046', '0053', '00559', '0056', '0065', '0068', '00700',
       '0077', '00800', '0091', '009891', '00am', '00noon', '00pm', '01',
       '01029787', '011', '0110486', '0118', '0119', '012', '0120',
       '01207673477', '013', '0175', '018', '01810'], dtype=object)

In [11]:
[word for word in feature_names if word in ["python", "java", "sql", "react", "mongodb", "fastapi"]]

['java', 'mongodb', 'python', 'react', 'sql']

In [12]:
len(feature_names)

40311

In [13]:
first_resume_vector = tfidf_matrix[0]

In [14]:
first_resume_vector

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 310 stored elements and shape (1, 40311)>

In [15]:
first_resume_vector.toarray()

array([[0., 0., 0., ..., 0., 0., 0.]], shape=(1, 40311))

In [16]:
job_description = """
We are looking for a Python developer with experience in
Python, SQL, MongoDB, FastAPI, REST API, React and JavaScript.
The candidate should have experience in backend development,
database management and web application development.
"""

In [17]:
job_vector = vectorizer.transform([job_description])

In [18]:
from sklearn.metrics.pairwise import cosine_similarity

In [19]:
similarity_scores = cosine_similarity(
    job_vector,
    tfidf_matrix
)

In [20]:
similarity_scores.shape

(1, 2481)

In [21]:
scores = similarity_scores[0]

In [22]:
scores[:10]

array([0.00796276, 0.01554907, 0.03796819, 0.01413143, 0.01613122,
       0.01204207, 0.04035995, 0.0172283 , 0.03100474, 0.02283916])

In [23]:
match_percentage = scores * 100

In [24]:
match_percentage[:10]

array([0.79627566, 1.55490681, 3.79681927, 1.4131425 , 1.61312184,
       1.20420667, 4.03599451, 1.72283012, 3.10047353, 2.28391598])

In [25]:
results = df.copy()

In [26]:
results["match_score"] = match_percentage

In [27]:
results = results.sort_values(
    "match_score",
    ascending=False
)

In [28]:
results[
    ["ID", "Category", "match_score"]
].head(20)

            ID                Category  match_score
925   62994611             AGRICULTURE    21.273043
1110  43311839              CONSULTANT    16.315918
1740  51588273             ENGINEERING    16.231933
229   36434348  INFORMATION-TECHNOLOGY    15.815803
1302  42156237           DIGITAL-MEDIA    14.860788
309   16186411  INFORMATION-TECHNOLOGY    14.822547
120   35990852                DESIGNER    14.613325
311   26746496  INFORMATION-TECHNOLOGY    13.918270
297   83816738  INFORMATION-TECHNOLOGY    13.492720
1797  10624813             ENGINEERING    13.443833
128   12415691                DESIGNER    13.215454
2393  12144825                AVIATION    13.138475
243   13385306  INFORMATION-TECHNOLOGY    13.134166
280   28126340  INFORMATION-TECHNOLOGY    12.810708
1748  27152464             ENGINEERING    12.698314
1745  28762662             ENGINEERING    12.615139
296   18187364  INFORMATION-TECHNOLOGY    12.447321
2182  39247950                 BANKING    12.298475
1781  11981094             ENGINEERING    12.215554
1217  21156767              CONSULTANT    12.167497

In [29]:
results[
    ["ID", "Category", "match_score"]
].head(10)

            ID                Category  match_score
925   62994611             AGRICULTURE    21.273043
1110  43311839              CONSULTANT    16.315918
1740  51588273             ENGINEERING    16.231933
229   36434348  INFORMATION-TECHNOLOGY    15.815803
1302  42156237           DIGITAL-MEDIA    14.860788
309   16186411  INFORMATION-TECHNOLOGY    14.822547
120   35990852                DESIGNER    14.613325
311   26746496  INFORMATION-TECHNOLOGY    13.918270
297   83816738  INFORMATION-TECHNOLOGY    13.492720
1797  10624813             ENGINEERING    13.443833

In [30]:
results["match_score"].describe()

count    2481.000000
mean        1.479223
std         1.879956
min         0.000000
25%         0.501308
50%         0.951717
75%         1.746957
max        21.273043
Name: match_score, dtype: float64

In [31]:
results["rank"] = range(1, len(results) + 1)

In [32]:
results[
    ["rank", "ID", "Category", "match_score"]
].head(10)

      rank        ID                Category  match_score
925      1  62994611             AGRICULTURE    21.273043
1110     2  43311839              CONSULTANT    16.315918
1740     3  51588273             ENGINEERING    16.231933
229      4  36434348  INFORMATION-TECHNOLOGY    15.815803
1302     5  42156237           DIGITAL-MEDIA    14.860788
309      6  16186411  INFORMATION-TECHNOLOGY    14.822547
120      7  35990852                DESIGNER    14.613325
311      8  26746496  INFORMATION-TECHNOLOGY    13.918270
297      9  83816738  INFORMATION-TECHNOLOGY    13.492720
1797    10  10624813             ENGINEERING    13.443833

In [33]:
job_description_2 = """
We are looking for a data analyst with experience in
Python, SQL, Excel, statistics, data visualization,
Pandas, NumPy and Power BI.
The candidate should be able to analyze datasets,
create reports and generate business insights.
"""

In [34]:
job_vector_2 = vectorizer.transform([job_description_2])

In [35]:
similarity_scores_2 = cosine_similarity(
    job_vector_2,
    tfidf_matrix
)

In [36]:
scores_2 = similarity_scores_2[0]

In [37]:
results_2 = df.copy()
results_2["match_score"] = scores_2 * 100

In [38]:
results_2 = results_2.sort_values(
    "match_score",
    ascending=False
)

In [39]:
results_2[
    ["ID", "Category", "match_score"]
].head(10)

            ID                Category  match_score
1217  21156767              CONSULTANT    25.570301
1302  42156237           DIGITAL-MEDIA    23.644083
1338  18448085              AUTOMOBILE    20.524681
925   62994611             AGRICULTURE    20.000423
1760  12011623             ENGINEERING    16.991972
1141  30863060              CONSULTANT    16.544538
563   25397102    BUSINESS-DEVELOPMENT    14.234983
777   26585242              HEALTHCARE    13.933283
1090  24610685                   SALES    13.735236
331   18067556  INFORMATION-TECHNOLOGY    13.346146

In [40]:
results[
    ["ID", "Category", "match_score", "rank"]
].to_csv(
    "../data/processed/tfidf_matching_results.csv",
    index=False
)

In [41]:
import os

os.path.exists(
    "../data/processed/tfidf_matching_results.csv"
)

True

In [42]:
vectorizer_v2 = TfidfVectorizer(
    ngram_range=(1, 2)
)

In [43]:
tfidf_matrix_v2 = vectorizer_v2.fit_transform(
    df["processed_resume"]
)

In [44]:
tfidf_matrix_v2.shape

(2481, 739699)

In [45]:
job_vector_v2 = vectorizer_v2.transform(
    [job_description]
)

In [46]:
similarity_v2 = cosine_similarity(
    job_vector_v2,
    tfidf_matrix_v2
)[0]

In [47]:
results_v2 = df.copy()

results_v2["match_score"] = similarity_v2 * 100

In [48]:
results_v2 = results_v2.sort_values(
    "match_score",
    ascending=False
)

In [49]:
results_v2[
    ["ID", "Category", "match_score"]
].head(10)

            ID                Category  match_score
1110  43311839              CONSULTANT     9.794216
925   62994611             AGRICULTURE     9.418683
229   36434348  INFORMATION-TECHNOLOGY     9.393453
309   16186411  INFORMATION-TECHNOLOGY     9.072297
297   83816738  INFORMATION-TECHNOLOGY     8.728680
1745  28762662             ENGINEERING     8.348840
311   26746496  INFORMATION-TECHNOLOGY     8.218218
296   18187364  INFORMATION-TECHNOLOGY     7.654663
243   13385306  INFORMATION-TECHNOLOGY     7.621759
1781  11981094             ENGINEERING     7.519562