In [1]:
import pandas as pd

df = pd.read_csv("../data/processed/processed_resume.csv")

df.shape

(2481, 6)

In [2]:
skills = [
    "python",
    "java",
    "c++",
    "javascript",
    "typescript",
    "html",
    "css",
    "react",
    "node.js",
    "nodejs",
    "express",
    "fastapi",
    "flask",
    "django",
    "sql",
    "mysql",
    "mongodb",
    "postgresql",
    "oracle",
    "redis",
    "git",
    "github",
    "docker",
    "aws",
    "azure",
    "linux",
    "excel",
    "power bi",
    "tableau",
    "pandas",
    "numpy",
    "scikit-learn",
    "tensorflow",
    "pytorch",
    "machine learning",
    "deep learning",
    "natural language processing",
    "nlp",
    "data analysis",
    "data visualization",
    "rest api",
    "rest",
    "api"
]

In [3]:
len(skills)

43

In [20]:
def extract_skills(text):
    found_skills = []

    text = text.lower()

    for skill in skills:
        if skill in text:
            found_skills.append(skill)

    # Sort longest skills first
    found_skills.sort(key=len, reverse=True)

    final_skills = []

    for skill in found_skills:
        if not any(skill in existing for existing in final_skills):
            final_skills.append(skill)

    return final_skills

In [5]:
text = df["clean_resume"].iloc[0]

extract_skills(text)

['aws', 'data analysis']

In [6]:
df["extracted_skills"] = df["clean_resume"].apply(extract_skills)

In [7]:
df[["ID", "Category", "extracted_skills"]].head()

         ID Category      extracted_skills
0  16852973       HR  [aws, data analysis]
1  22323967       HR                 [git]
2  33176873       HR      [express, excel]
3  27018550       HR               [excel]
4  17812897       HR          [aws, excel]

In [8]:
df["skill_count"] = df["extracted_skills"].apply(len)

In [9]:
df[["ID", "Category", "skill_count"]].head(10)

         ID Category  skill_count
0  16852973       HR            2
1  22323967       HR            1
2  33176873       HR            2
3  27018550       HR            1
4  17812897       HR            2
5  11592605       HR            1
6  25824789       HR            1
7  15375009       HR            1
8  11847784       HR            2
9  32896934       HR            1

In [10]:
df["skill_count"].describe()

count    2481.000000
mean        1.997985
std         1.688074
min         0.000000
25%         1.000000
50%         2.000000
75%         3.000000
max        18.000000
Name: skill_count, dtype: float64

In [11]:
from collections import Counter

all_skills = []

for skill_list in df["extracted_skills"]:
    all_skills.extend(skill_list)

skill_counts = Counter(all_skills)

In [12]:
skill_counts.most_common(20)

[('excel', 1614),
 ('rest', 937),
 ('api', 469),
 ('git', 330),
 ('aws', 302),
 ('sql', 191),
 ('oracle', 171),
 ('html', 158),
 ('data analysis', 126),
 ('express', 111),
 ('java', 98),
 ('linux', 87),
 ('css', 86),
 ('javascript', 56),
 ('python', 40),
 ('mysql', 39),
 ('react', 35),
 ('tableau', 26),
 ('machine learning', 12),
 ('azure', 11)]

In [13]:
skill_frequency = pd.DataFrame(
    skill_counts.items(),
    columns=["skill", "count"]
)

skill_frequency = skill_frequency.sort_values(
    "count",
    ascending=False
)

skill_frequency.head(20)

               skill  count
4              excel   1614
5               rest    937
7                api    469
2                git    330
0                aws    302
9                sql    191
6             oracle    171
13              html    158
1      data analysis    126
3            express    111
8               java     98
15             linux     87
14               css     86
12        javascript     56
18            python     40
17             mysql     39
16             react     35
11           tableau     26
27  machine learning     12
21             azure     11

In [14]:
df.to_csv(
    "../data/processed/resume_skills.csv",
    index=False
)

In [15]:
import os

os.path.exists("../data/processed/resume_skills.csv")

True

In [16]:
job_description = """
We are looking for a Python developer with experience in
Python, SQL, MongoDB, FastAPI, REST API, React and JavaScript.
The candidate should have experience in backend development,
database management and web application development.
"""

In [17]:
required_skills = extract_skills(job_description)

required_skills

['python',
 'java',
 'javascript',
 'react',
 'fastapi',
 'sql',
 'mongodb',
 'rest api',
 'rest',
 'api']

In [18]:
required_skills = list(set(required_skills))

required_skills

['python',
 'rest',
 'fastapi',
 'java',
 'sql',
 'javascript',
 'react',
 'rest api',
 'api',
 'mongodb']

In [19]:
len(required_skills)

10

In [21]:
df["extracted_skills"] = df["clean_resume"].apply(extract_skills)

In [22]:
job_description = """
We are looking for a Python developer with experience in
Python, SQL, MongoDB, FastAPI, REST API, React and JavaScript.
The candidate should have experience in backend development,
database management and web application development.
"""

required_skills = extract_skills(job_description)

required_skills

['javascript', 'rest api', 'fastapi', 'mongodb', 'python', 'react', 'sql']

In [23]:
len(required_skills)

7

In [24]:
for skill in required_skills:
    print(skill)

javascript
rest api
fastapi
mongodb
python
react
sql

In [25]:
candidate_skills = df["extracted_skills"].iloc[0]

candidate_skills

['data analysis', 'aws']

In [26]:
matched_skills = list(
    set(candidate_skills) & set(required_skills)
)

matched_skills

[]

In [27]:
missing_skills = list(
    set(required_skills) - set(candidate_skills)
)

missing_skills

['python', 'fastapi', 'sql', 'javascript', 'react', 'rest api', 'mongodb']

In [28]:
skill_coverage = (
    len(matched_skills) / len(required_skills)
) * 100

skill_coverage

0.0

In [29]:
def calculate_skill_match(candidate_skills, required_skills):
    
    candidate_skills = set(candidate_skills)
    required_skills = set(required_skills)
    
    matched = list(candidate_skills & required_skills)
    missing = list(required_skills - candidate_skills)
    
    if len(required_skills) > 0:
        coverage = (
            len(matched) / len(required_skills)
        ) * 100
    else:
        coverage = 0
    
    return matched, missing, coverage

In [30]:
matched, missing, coverage = calculate_skill_match(
    df["extracted_skills"].iloc[0],
    required_skills
)

print("Matched Skills:", matched)
print("Missing Skills:", missing)
print("Skill Coverage:", coverage)

Matched Skills: []
Missing Skills: ['python', 'fastapi', 'sql', 'javascript', 'react', 'rest api', 'mongodb']
Skill Coverage: 0.0

In [31]:
for i in range(20):
    candidate_skills = set(df["extracted_skills"].iloc[i])
    matched = candidate_skills & set(required_skills)

    if matched:
        print("Candidate:", i)
        print("Matched:", matched)

In [32]:
for skill in required_skills:
    count = df["clean_resume"].str.contains(
        skill,
        case=False,
        na=False
    ).sum()

    print(skill, ":", count)

javascript : 56
rest api : 6
fastapi : 0
mongodb : 4
python : 40
react : 35
sql : 191

In [33]:
df[["ID", "Category", "extracted_skills"]].head(20)

          ID Category       extracted_skills
0   16852973       HR   [data analysis, aws]
1   22323967       HR                  [git]
2   33176873       HR       [express, excel]
3   27018550       HR                [excel]
4   17812897       HR           [excel, aws]
5   11592605       HR                [excel]
6   25824789       HR                 [rest]
7   15375009       HR                  [aws]
8   11847784       HR           [excel, aws]
9   32896934       HR                  [aws]
10  29149998       HR          [oracle, aws]
11  11480899       HR                     []
12  23155093       HR                [excel]
13  11763983       HR           [excel, aws]
14  27490876       HR                  [aws]
15  32977530       HR           [excel, api]
16  93002334       HR                [excel]
17  24184357       HR      [excel, aws, api]
18  73077810       HR                     []
19  13879043       HR  [data analysis, rest]

In [34]:
print(required_skills)

['javascript', 'rest api', 'fastapi', 'mongodb', 'python', 'react', 'sql']

In [35]:
print(df["extracted_skills"].iloc[0])

['data analysis', 'aws']

In [36]:
for skill in required_skills:
    count = df["clean_resume"].str.contains(
        skill,
        case=False,
        na=False
    ).sum()
    print(skill, ":", count)

javascript : 56
rest api : 6
fastapi : 0
mongodb : 4
python : 40
react : 35
sql : 191

In [37]:
required_set = set(required_skills)

for i in range(len(df)):
    candidate_skills = set(df["extracted_skills"].iloc[i])
    matched = candidate_skills & required_set

    if matched:
        print("Candidate index:", i)
        print("ID:", df["ID"].iloc[i])
        print("Category:", df["Category"].iloc[i])
        print("Candidate skills:", df["extracted_skills"].iloc[i])
        print("Matched skills:", list(matched))
        break

Candidate index: 41
ID: 59962788
Category: HR
Candidate skills: ['java', 'sql']
Matched skills: ['sql']

In [38]:
def calculate_skill_match(candidate_skills, required_skills):
    
    candidate_skills = set(candidate_skills)
    required_skills = set(required_skills)
    
    matched = list(candidate_skills & required_skills)
    missing = list(required_skills - candidate_skills)
    
    if len(required_skills) > 0:
        coverage = (
            len(matched) / len(required_skills)
        ) * 100
    else:
        coverage = 0
    
    return matched, missing, coverage

In [39]:
matched, missing, coverage = calculate_skill_match(
    df["extracted_skills"].iloc[41],
    required_skills
)

print("Matched Skills:", matched)
print("Missing Skills:", missing)
print("Skill Coverage:", coverage)

Matched Skills: ['sql']
Missing Skills: ['python', 'fastapi', 'javascript', 'react', 'rest api', 'mongodb']
Skill Coverage: 14.285714285714285

In [40]:
df["matched_skills"] = df["extracted_skills"].apply(
    lambda x: calculate_skill_match(
        x,
        required_skills
    )[0]
)

In [41]:
df["missing_skills"] = df["extracted_skills"].apply(
    lambda x: calculate_skill_match(
        x,
        required_skills
    )[1]
)

In [42]:
df["skill_coverage"] = df["extracted_skills"].apply(
    lambda x: calculate_skill_match(
        x,
        required_skills
    )[2]
)

In [43]:
df[
    [
        "ID",
        "Category",
        "extracted_skills",
        "matched_skills",
        "missing_skills",
        "skill_coverage"
    ]
].head(10)

,ID,Category,extracted_skills,matched_skills,missing_skills,skill_coverage
0,16852973,HR,"[data analysis, aws]",[],"[python, fastapi, sql, javascript, react, rest...",0.0
1,22323967,HR,[git],[],"[python, fastapi, sql, javascript, react, rest...",0.0
2,33176873,HR,"[express, excel]",[],"[python, fastapi, sql, javascript, react, rest...",0.0
3,27018550,HR,[excel],[],"[python, fastapi, sql, javascript, react, rest...",0.0
4,17812897,HR,"[excel, aws]",[],"[python, fastapi, sql, javascript, react, rest...",0.0
5,11592605,HR,[excel],[],"[python, fastapi, sql, javascript, react, rest...",0.0
6,25824789,HR,[rest],[],"[python, fastapi, sql, javascript, react, rest...",0.0
7,15375009,HR,[aws],[],"[python, fastapi, sql, javascript, react, rest...",0.0
8,11847784,HR,"[excel, aws]",[],"[python, fastapi, sql, javascript, react, rest...",0.0
9,32896934,HR,[aws],[],"[python, fastapi, sql, javascript, react, rest...",0.0

In [44]:
matched_candidates = df[
    df["skill_coverage"] > 0
]

matched_candidates[
    [
        "ID",
        "Category",
        "extracted_skills",
        "matched_skills",
        "missing_skills",
        "skill_coverage"
    ]
].head(10)

,ID,Category,extracted_skills,matched_skills,missing_skills,skill_coverage
41,59962788,HR,"[java, sql]",[sql],"[python, fastapi, javascript, react, rest api,...",14.285714
78,16877897,HR,"[javascript, excel, html, rest, css, sql]","[sql, javascript]","[python, fastapi, react, rest api, mongodb]",28.571429
91,18297650,HR,"[oracle, linux, excel, java, sql, aws]",[sql],"[python, fastapi, javascript, react, rest api,...",14.285714
116,11919526,DESIGNER,"[javascript, oracle, excel, html, sql]","[sql, javascript]","[python, fastapi, react, rest api, mongodb]",28.571429
117,81011612,DESIGNER,"[data analysis, html, sql]",[sql],"[python, fastapi, javascript, react, rest api,...",14.285714
119,13774329,DESIGNER,"[react, rest, git]",[react],"[python, fastapi, sql, javascript, rest api, m...",14.285714
120,35990852,DESIGNER,"[javascript, mysql, html, rest, css, git]",[javascript],"[python, fastapi, sql, react, rest api, mongodb]",14.285714
126,10751444,DESIGNER,"[data analysis, python, linux, excel, git]",[python],"[fastapi, sql, javascript, react, rest api, mo...",14.285714
127,11807040,DESIGNER,"[react, excel, git]",[react],"[python, fastapi, sql, javascript, rest api, m...",14.285714
128,12415691,DESIGNER,"[express, python, oracle, mysql, linux, java, ...",[python],"[fastapi, sql, javascript, react, rest api, mo...",14.285714

In [45]:
matched_candidates = df[
    df["skill_coverage"] > 0
]

matched_candidates[
    [
        "ID",
        "Category",
        "extracted_skills",
        "matched_skills",
        "missing_skills",
        "skill_coverage"
    ]
].head(50)

,ID,Category,extracted_skills,matched_skills,missing_skills,skill_coverage
41,59962788,HR,"[java, sql]",[sql],"[python, fastapi, javascript, react, rest api,...",14.285714
78,16877897,HR,"[javascript, excel, html, rest, css, sql]","[sql, javascript]","[python, fastapi, react, rest api, mongodb]",28.571429
91,18297650,HR,"[oracle, linux, excel, java, sql, aws]",[sql],"[python, fastapi, javascript, react, rest api,...",14.285714
116,11919526,DESIGNER,"[javascript, oracle, excel, html, sql]","[sql, javascript]","[python, fastapi, react, rest api, mongodb]",28.571429
117,81011612,DESIGNER,"[data analysis, html, sql]",[sql],"[python, fastapi, javascript, react, rest api,...",14.285714
119,13774329,DESIGNER,"[react, rest, git]",[react],"[python, fastapi, sql, javascript, rest api, m...",14.285714
120,35990852,DESIGNER,"[javascript, mysql, html, rest, css, git]",[javascript],"[python, fastapi, sql, react, rest api, mongodb]",14.285714
126,10751444,DESIGNER,"[data analysis, python, linux, excel, git]",[python],"[fastapi, sql, javascript, react, rest api, mo...",14.285714
127,11807040,DESIGNER,"[react, excel, git]",[react],"[python, fastapi, sql, javascript, rest api, m...",14.285714
128,12415691,DESIGNER,"[express, python, oracle, mysql, linux, java, ...",[python],"[fastapi, sql, javascript, react, rest api, mo...",14.285714
132,29524570,DESIGNER,"[data analysis, oracle, react, excel, html, cs...","[sql, react]","[python, fastapi, javascript, rest api, mongodb]",28.571429
163,30968749,DESIGNER,"[excel, rest, sql]",[sql],"[python, fastapi, javascript, react, rest api,...",14.285714
182,34317538,DESIGNER,"[data visualization, data analysis, excel, htm...",[sql],"[python, fastapi, javascript, react, rest api,...",14.285714
223,19796840,INFORMATION-TECHNOLOGY,"[oracle, sql, aws]",[sql],"[python, fastapi, javascript, react, rest api,...",14.285714
224,15651486,INFORMATION-TECHNOLOGY,"[express, linux, sql, api]",[sql],"[python, fastapi, javascript, react, rest api,...",14.285714
226,12045067,INFORMATION-TECHNOLOGY,[react],[react],"[python, fastapi, sql, javascript, rest api, m...",14.285714
227,13836471,INFORMATION-TECHNOLOGY,[sql],[sql],"[python, fastapi, javascript, react, rest api,...",14.285714
228,14789139,INFORMATION-TECHNOLOGY,[sql],[sql],"[python, fastapi, javascript, react, rest api,...",14.285714
229,36434348,INFORMATION-TECHNOLOGY,"[oracle, html, sql]",[sql],"[python, fastapi, javascript, react, rest api,...",14.285714
230,27536013,INFORMATION-TECHNOLOGY,"[data analysis, oracle, sql]",[sql],"[python, fastapi, javascript, react, rest api,...",14.285714
231,18301617,INFORMATION-TECHNOLOGY,"[linux, excel, sql, api]",[sql],"[python, fastapi, javascript, react, rest api,...",14.285714
239,41344156,INFORMATION-TECHNOLOGY,"[data analysis, sql, git]",[sql],"[python, fastapi, javascript, react, rest api,...",14.285714
241,10247517,INFORMATION-TECHNOLOGY,"[excel, rest, sql]",[sql],"[python, fastapi, javascript, react, rest api,...",14.285714
242,25959103,INFORMATION-TECHNOLOGY,"[sql, api]",[sql],"[python, fastapi, javascript, react, rest api,...",14.285714
243,13385306,INFORMATION-TECHNOLOGY,"[tableau, oracle, sql]",[sql],"[python, fastapi, javascript, react, rest api,...",14.285714
247,11580408,INFORMATION-TECHNOLOGY,"[excel, sql]",[sql],"[python, fastapi, javascript, react, rest api,...",14.285714
249,12635195,INFORMATION-TECHNOLOGY,"[data analysis, javascript, python]","[python, javascript]","[fastapi, sql, react, rest api, mongodb]",28.571429
250,32959732,INFORMATION-TECHNOLOGY,"[tableau, azure, linux, rest, sql, api]",[sql],"[python, fastapi, javascript, react, rest api,...",14.285714
251,17688766,INFORMATION-TECHNOLOGY,"[sql, api]",[sql],"[python, fastapi, javascript, react, rest api,...",14.285714
252,20024870,INFORMATION-TECHNOLOGY,"[excel, java, html, css, sql]",[sql],"[python, fastapi, javascript, react, rest api,...",14.285714
257,37764298,INFORMATION-TECHNOLOGY,"[excel, sql]",[sql],"[python, fastapi, javascript, react, rest api,...",14.285714
258,90867631,INFORMATION-TECHNOLOGY,"[oracle, excel, html, rest, sql, git]",[sql],"[python, fastapi, javascript, react, rest api,...",14.285714
265,20001721,INFORMATION-TECHNOLOGY,"[linux, excel, rest, sql]",[sql],"[python, fastapi, javascript, react, rest api,...",14.285714
267,13405733,INFORMATION-TECHNOLOGY,"[python, oracle, excel, sql, git]","[python, sql]","[fastapi, javascript, react, rest api, mongodb]",28.571429
271,17987433,INFORMATION-TECHNOLOGY,"[react, api]",[react],"[python, fastapi, sql, javascript, rest api, m...",14.285714
272,10553553,INFORMATION-TECHNOLOGY,"[excel, sql, api]",[sql],"[python, fastapi, javascript, react, rest api,...",14.285714
274,18176523,INFORMATION-TECHNOLOGY,[sql],[sql],"[python, fastapi, javascript, react, rest api,...",14.285714
276,70089206,INFORMATION-TECHNOLOGY,"[javascript, oracle, linux, sql]","[sql, javascript]","[python, fastapi, react, rest api, mongodb]",28.571429
278,57002858,INFORMATION-TECHNOLOGY,"[excel, rest, sql]",[sql],"[python, fastapi, javascript, react, rest api,...",14.285714
280,28126340,INFORMATION-TECHNOLOGY,"[javascript, oracle, mysql, linux, html, css]",[javascript],"[python, fastapi, sql, react, rest api, mongodb]",14.285714
281,37242217,INFORMATION-TECHNOLOGY,"[javascript, express, oracle, mysql, linux, ht...",[javascript],"[python, fastapi, sql, react, rest api, mongodb]",14.285714
282,10089434,INFORMATION-TECHNOLOGY,"[azure, linux, java, html, css, sql]",[sql],"[python, fastapi, javascript, react, rest api,...",14.285714
283,11957080,INFORMATION-TECHNOLOGY,"[data analysis, linux, excel, html, sql]",[sql],"[python, fastapi, javascript, react, rest api,...",14.285714
286,64017585,INFORMATION-TECHNOLOGY,"[react, linux, git]",[react],"[python, fastapi, sql, javascript, rest api, m...",14.285714
290,51639418,INFORMATION-TECHNOLOGY,"[oracle, linux, sql, git]",[sql],"[python, fastapi, javascript, react, rest api,...",14.285714
291,20674668,INFORMATION-TECHNOLOGY,"[javascript, python, oracle, excel, html, css,...","[python, sql, javascript]","[fastapi, mongodb, rest api, react]",42.857143
294,22776912,INFORMATION-TECHNOLOGY,"[excel, sql, git, api]",[sql],"[python, fastapi, javascript, react, rest api,...",14.285714
296,18187364,INFORMATION-TECHNOLOGY,"[oracle, linux, rest, sql]",[sql],"[python, fastapi, javascript, react, rest api,...",14.285714
297,83816738,INFORMATION-TECHNOLOGY,"[javascript, postgresql, mongodb, oracle, gith...","[javascript, mongodb, react]","[python, sql, fastapi, rest api]",42.857143
298,20824105,INFORMATION-TECHNOLOGY,"[express, python, oracle, linux, aws]",[python],"[fastapi, sql, javascript, react, rest api, mo...",14.285714

In [46]:
skill_results = matched_candidates.sort_values(
    "skill_coverage",
    ascending=False
)

skill_results[
    [
        "ID",
        "Category",
        "matched_skills",
        "missing_skills",
        "skill_coverage"
    ]
].head(15)

,ID,Category,matched_skills,missing_skills,skill_coverage
925,62994611,AGRICULTURE,"[python, sql, javascript, react, mongodb]","[fastapi, rest api]",71.428571
1797,10624813,ENGINEERING,"[python, sql, javascript, mongodb]","[fastapi, rest api, react]",57.142857
291,20674668,INFORMATION-TECHNOLOGY,"[python, sql, javascript]","[fastapi, mongodb, rest api, react]",42.857143
297,83816738,INFORMATION-TECHNOLOGY,"[javascript, mongodb, react]","[python, sql, fastapi, rest api]",42.857143
1110,43311839,CONSULTANT,"[sql, javascript, rest api]","[python, fastapi, mongodb, react]",42.857143
1171,95429627,CONSULTANT,"[python, sql, javascript]","[fastapi, mongodb, rest api, react]",42.857143
1730,20566550,ENGINEERING,"[python, sql, react]","[mongodb, fastapi, javascript, rest api]",42.857143
315,10265057,INFORMATION-TECHNOLOGY,"[python, sql]","[fastapi, javascript, react, rest api, mongodb]",28.571429
563,25397102,BUSINESS-DEVELOPMENT,"[python, sql]","[fastapi, javascript, react, rest api, mongodb]",28.571429
843,22488036,FITNESS,"[python, sql]","[fastapi, javascript, react, rest api, mongodb]",28.571429
986,41152404,BPO,"[sql, javascript]","[python, fastapi, react, rest api, mongodb]",28.571429
547,44115326,ADVOCATE,"[sql, react]","[python, fastapi, javascript, rest api, mongodb]",28.571429
706,98300955,HEALTHCARE,"[sql, javascript]","[python, fastapi, react, rest api, mongodb]",28.571429
116,11919526,DESIGNER,"[sql, javascript]","[python, fastapi, react, rest api, mongodb]",28.571429
276,70089206,INFORMATION-TECHNOLOGY,"[sql, javascript]","[python, fastapi, react, rest api, mongodb]",28.571429

In [47]:
skill_results = df.sort_values(
    "skill_coverage",
    ascending=False
).copy()

In [48]:
skill_results["skill_rank"] = range(
    1,
    len(skill_results) + 1
)

In [49]:
skill_results[
    [
        "skill_rank",
        "ID",
        "Category",
        "matched_skills",
        "missing_skills",
        "skill_coverage"
    ]
].head(15)

,skill_rank,ID,Category,matched_skills,missing_skills,skill_coverage
925,1,62994611,AGRICULTURE,"[python, sql, javascript, react, mongodb]","[fastapi, rest api]",71.428571
1797,2,10624813,ENGINEERING,"[python, sql, javascript, mongodb]","[fastapi, rest api, react]",57.142857
1110,3,43311839,CONSULTANT,"[sql, javascript, rest api]","[python, fastapi, mongodb, react]",42.857143
291,4,20674668,INFORMATION-TECHNOLOGY,"[python, sql, javascript]","[fastapi, mongodb, rest api, react]",42.857143
1171,5,95429627,CONSULTANT,"[python, sql, javascript]","[fastapi, mongodb, rest api, react]",42.857143
297,6,83816738,INFORMATION-TECHNOLOGY,"[javascript, mongodb, react]","[python, sql, fastapi, rest api]",42.857143
1730,7,20566550,ENGINEERING,"[python, sql, react]","[mongodb, fastapi, javascript, rest api]",42.857143
315,8,10265057,INFORMATION-TECHNOLOGY,"[python, sql]","[fastapi, javascript, react, rest api, mongodb]",28.571429
928,9,11813872,AGRICULTURE,"[python, sql]","[fastapi, javascript, react, rest api, mongodb]",28.571429
986,10,41152404,BPO,"[sql, javascript]","[python, fastapi, react, rest api, mongodb]",28.571429
1130,11,15281412,CONSULTANT,"[sql, javascript]","[python, fastapi, react, rest api, mongodb]",28.571429
661,12,14871762,BUSINESS-DEVELOPMENT,"[python, sql]","[fastapi, javascript, react, rest api, mongodb]",28.571429
2075,13,36107065,PUBLIC-RELATIONS,"[sql, react]","[python, fastapi, javascript, rest api, mongodb]",28.571429
276,14,70089206,INFORMATION-TECHNOLOGY,"[sql, javascript]","[python, fastapi, react, rest api, mongodb]",28.571429
563,15,25397102,BUSINESS-DEVELOPMENT,"[python, sql]","[fastapi, javascript, react, rest api, mongodb]",28.571429

In [50]:
skill_results[
    [
        "skill_rank",
        "ID",
        "Category",
        "extracted_skills",
        "matched_skills",
        "missing_skills",
        "skill_coverage"
    ]
].to_csv(
    "../data/processed/skill_matching_results.csv",
    index=False
)

In [51]:
import os

os.path.exists(
    "../data/processed/skill_matching_results.csv"
)

True

In [52]:
import pandas as pd

tfidf_results = pd.read_csv(
    "../data/processed/tfidf_matching_results.csv"
)

skill_results = pd.read_csv(
    "../data/processed/skill_matching_results.csv"
)

print("TF-IDF:", tfidf_results.shape)
print("Skills:", skill_results.shape)

TF-IDF: (2481, 4)
Skills: (2481, 7)

In [53]:
print(tfidf_results["ID"].head())
print(skill_results["ID"].head())

0    62994611
1    43311839
2    51588273
3    36434348
4    42156237
Name: ID, dtype: int64
0    62994611
1    10624813
2    43311839
3    20674668
4    95429627
Name: ID, dtype: int64

In [54]:
print("TF-IDF duplicate IDs:", tfidf_results["ID"].duplicated().sum())
print("Skill duplicate IDs:", skill_results["ID"].duplicated().sum())

TF-IDF duplicate IDs: 0
Skill duplicate IDs: 0

In [55]:
combined_results = tfidf_results.merge(
    skill_results[
        [
            "ID",
            "matched_skills",
            "missing_skills",
            "skill_coverage"
        ]
    ],
    on="ID",
    how="inner"
)

In [56]:
combined_results.shape

(2481, 7)

In [57]:
combined_results[
    [
        "ID",
        "Category",
        "match_score",
        "skill_coverage",
        "matched_skills",
        "missing_skills"
    ]
].head(10)

,ID,Category,match_score,skill_coverage,matched_skills,missing_skills
0,62994611,AGRICULTURE,21.273043,71.428571,"['python', 'sql', 'javascript', 'react', 'mong...","['fastapi', 'rest api']"
1,43311839,CONSULTANT,16.315918,42.857143,"['sql', 'javascript', 'rest api']","['python', 'fastapi', 'mongodb', 'react']"
2,51588273,ENGINEERING,16.231933,28.571429,"['sql', 'javascript']","['python', 'fastapi', 'react', 'rest api', 'mo..."
3,36434348,INFORMATION-TECHNOLOGY,15.815803,14.285714,['sql'],"['python', 'fastapi', 'javascript', 'react', '..."
4,42156237,DIGITAL-MEDIA,14.860788,28.571429,"['python', 'javascript']","['fastapi', 'sql', 'react', 'rest api', 'mongo..."
5,16186411,INFORMATION-TECHNOLOGY,14.822547,14.285714,['javascript'],"['python', 'fastapi', 'sql', 'react', 'rest ap..."
6,35990852,DESIGNER,14.613325,14.285714,['javascript'],"['python', 'fastapi', 'sql', 'react', 'rest ap..."
7,26746496,INFORMATION-TECHNOLOGY,13.918270,14.285714,['javascript'],"['python', 'fastapi', 'sql', 'react', 'rest ap..."
8,83816738,INFORMATION-TECHNOLOGY,13.492720,42.857143,"['javascript', 'mongodb', 'react']","['python', 'sql', 'fastapi', 'rest api']"
9,10624813,ENGINEERING,13.443833,57.142857,"['python', 'sql', 'javascript', 'mongodb']","['fastapi', 'rest api', 'react']"

In [58]:
combined_results["overall_score"] = (
    0.5 * combined_results["match_score"]
    + 0.5 * combined_results["skill_coverage"]
)

In [59]:
combined_results = combined_results.sort_values(
    "overall_score",
    ascending=False
).reset_index(drop=True)

In [60]:
combined_results["overall_rank"] = range(
    1,
    len(combined_results) + 1
)

In [61]:
combined_results[
    [
        "overall_rank",
        "ID",
        "Category",
        "match_score",
        "skill_coverage",
        "overall_score",
        "matched_skills",
        "missing_skills"
    ]
].head(10)

,overall_rank,ID,Category,match_score,skill_coverage,overall_score,matched_skills,missing_skills
0,1,62994611,AGRICULTURE,21.273043,71.428571,46.350807,"['python', 'sql', 'javascript', 'react', 'mong...","['fastapi', 'rest api']"
1,2,10624813,ENGINEERING,13.443833,57.142857,35.293345,"['python', 'sql', 'javascript', 'mongodb']","['fastapi', 'rest api', 'react']"
2,3,43311839,CONSULTANT,16.315918,42.857143,29.586530,"['sql', 'javascript', 'rest api']","['python', 'fastapi', 'mongodb', 'react']"
3,4,83816738,INFORMATION-TECHNOLOGY,13.492720,42.857143,28.174931,"['javascript', 'mongodb', 'react']","['python', 'sql', 'fastapi', 'rest api']"
4,5,20674668,INFORMATION-TECHNOLOGY,9.245386,42.857143,26.051265,"['python', 'sql', 'javascript']","['fastapi', 'mongodb', 'rest api', 'react']"
5,6,95429627,CONSULTANT,7.737766,42.857143,25.297454,"['python', 'sql', 'javascript']","['fastapi', 'mongodb', 'rest api', 'react']"
6,7,20566550,ENGINEERING,3.600185,42.857143,23.228664,"['python', 'sql', 'react']","['mongodb', 'fastapi', 'javascript', 'rest api']"
7,8,51588273,ENGINEERING,16.231933,28.571429,22.401681,"['sql', 'javascript']","['python', 'fastapi', 'react', 'rest api', 'mo..."
8,9,42156237,DIGITAL-MEDIA,14.860788,28.571429,21.716108,"['python', 'javascript']","['fastapi', 'sql', 'react', 'rest api', 'mongo..."
9,10,12144825,AVIATION,13.138475,28.571429,20.854952,"['python', 'javascript']","['fastapi', 'sql', 'react', 'rest api', 'mongo..."

In [62]:
combined_results["overall_rank"] = range(
    1,
    len(combined_results) + 1
)

In [63]:
combined_results[
    [
        "overall_rank",
        "ID",
        "Category",
        "match_score",
        "skill_coverage",
        "overall_score",
        "matched_skills",
        "missing_skills"
    ]
].head(10)

,overall_rank,ID,Category,match_score,skill_coverage,overall_score,matched_skills,missing_skills
0,1,62994611,AGRICULTURE,21.273043,71.428571,46.350807,"['python', 'sql', 'javascript', 'react', 'mong...","['fastapi', 'rest api']"
1,2,10624813,ENGINEERING,13.443833,57.142857,35.293345,"['python', 'sql', 'javascript', 'mongodb']","['fastapi', 'rest api', 'react']"
2,3,43311839,CONSULTANT,16.315918,42.857143,29.586530,"['sql', 'javascript', 'rest api']","['python', 'fastapi', 'mongodb', 'react']"
3,4,83816738,INFORMATION-TECHNOLOGY,13.492720,42.857143,28.174931,"['javascript', 'mongodb', 'react']","['python', 'sql', 'fastapi', 'rest api']"
4,5,20674668,INFORMATION-TECHNOLOGY,9.245386,42.857143,26.051265,"['python', 'sql', 'javascript']","['fastapi', 'mongodb', 'rest api', 'react']"
5,6,95429627,CONSULTANT,7.737766,42.857143,25.297454,"['python', 'sql', 'javascript']","['fastapi', 'mongodb', 'rest api', 'react']"
6,7,20566550,ENGINEERING,3.600185,42.857143,23.228664,"['python', 'sql', 'react']","['mongodb', 'fastapi', 'javascript', 'rest api']"
7,8,51588273,ENGINEERING,16.231933,28.571429,22.401681,"['sql', 'javascript']","['python', 'fastapi', 'react', 'rest api', 'mo..."
8,9,42156237,DIGITAL-MEDIA,14.860788,28.571429,21.716108,"['python', 'javascript']","['fastapi', 'sql', 'react', 'rest api', 'mongo..."
9,10,12144825,AVIATION,13.138475,28.571429,20.854952,"['python', 'javascript']","['fastapi', 'sql', 'react', 'rest api', 'mongo..."

In [64]:
combined_results[
    [
        "overall_rank",
        "ID",
        "Category",
        "match_score",
        "skill_coverage",
        "overall_score",
        "matched_skills",
        "missing_skills"
    ]
].to_csv(
    "../data/processed/overall_candidate_ranking.csv",
    index=False
)