In [1]:
import pandas as pd

In [2]:
df = pd.read_csv( "../data/processed/processed_resume.csv"
)

In [3]:
print(df.shape)

(2481, 6)

In [4]:
print(df["clean_resume"].iloc[0])

hr administrator marketing associate hr administrator summary dedicated customer service manager with 15  years of experience in hospitality and customer service management  respected builder and leader of customer focused teams  strives to instill a shared  enthusiastic commitment to customer service  highlights focused on customer satisfaction team management marketing savvy conflict resolution techniques training and development skilled multi tasker client relations specialist accomplishments missouri dot supervisor training certification certified by ihg in customer loyalty and marketing by segment hilton worldwide general manager training certification accomplished trainer for cross server hospitality systems such as hilton onq   micros opera pms   fidelio opera reservation system  ors    holidex completed courses and seminars in customer service  sales strategies  inventory control  loss prevention  safety  time management  leadership and performance assessment  experience hr administrator marketing associate hr administrator dec 2013 to current company name   city   state helps to develop policies  directs and coordinates activities such as employment  compensation  labor relations  benefits  training  and employee services  prepares employee separation notices and related documentation keeps records of benefits plans participation such as insurance and pension plan  personnel transactions such as hires  promotions  transfers  performance reviews  and terminations  and employee statistics for government reporting  advises management in appropriate resolution of employee relations issues  administers benefits programs such as life  health  dental  insurance  pension plans  vacation  sick leave  leave of absence  and employee assistance  marketing associate designed and created marketing collateral for sales meetings  trade shows and company executives  managed the in house advertising program consisting of print and media collateral pieces  assisted in the complete design and launch of the company s website in 2 months  created an official company page on facebook to facilitate interaction with customers  analyzed ratings and programming features of competitors to evaluate the effectiveness of marketing strategies  advanced medical claims analyst mar 2012 to dec 2013 company name   city   state reviewed medical bills for the accuracy of the treatments  tests  and hospital stays prior to sanctioning the claims  trained to interpret the codes  icd 9  cpt  and terminology commonly used in medical billing to fully understand the paperwork that is submitted by healthcare providers  required to have organizational and analytical skills as well as computer skills  knowledge of medical terminology and procedures  statistics  billing standards  data analysis and laws regarding medical billing  assistant general manager jun 2010 to dec 2010 company name   city   state performed duties including but not limited to  budgeting and financial management  accounting  human resources  payroll and purchasing  established and maintained close working relationships with all departments of the hotel to ensure maximum operation  productivity  morale and guest service  handled daily operations and reported directly to the corporate office  hired and trained staff on overall objectives and goals with an emphasis on high customer service  marketing and advertising  working on public relations with the media  government and local businesses and chamber of commerce  executive support   marketing assistant jul 2007 to jun 2010 company name   city   state provided assistance to various department heads   executive  marketing  customer service  human resources  managed front end operations to ensure friendly and efficient transactions  ensured the swift resolution of customer issues to preserve customer loyalty while complying with company policies  exemplified the second to none customer service delivery in all interactions with customers and potential clients  reservation   front office manager jun 2004 to jul 2007 company name   city   state owner  partner dec 2001 to may 2004 company name   city   state price integrity coordinator aug 1999 to dec 2001 company name   city   state education n a   business administration 1999 jefferson college   city   state business administration marketing   advertising high school diploma   college prep  studies 1998 sainte genevieve senior high   city   state awarded american shrubel leadership scholarship to jefferson college skills accounting  ads  advertising  analytical skills  benefits  billing  budgeting  clients  customer service  data analysis  delivery  documentation  employee relations  financial management  government relations  human resources  insurance  labor relations  layout  marketing  marketing collateral  medical billing  medical terminology  office  organizational  payroll  performance reviews  personnel  policies  posters  presentations  public relations  purchasing  reporting  statistics  website

In [5]:
import re

In [6]:
def extract_experience(text):
    patterns = [
        r'(\d+)\+?\s+years?\s+of\s+experience',
        r'(\d+)\+?\s+years?\s+experience',
        r'(\d+)\+?\s+years?\s+in'
    ]

    for pattern in patterns:
        match = re.search(pattern, text.lower())

        if match:
            return int(match.group(1))

    return 0

In [7]:
test_text = "I have 3 years of experience in Python and SQL."

print(extract_experience(test_text))

3

In [8]:
df["years_experience"] = df["clean_resume"].apply(
    extract_experience
)

In [9]:
df[
    ["ID", "Category", "years_experience"]
].head(20)

          ID Category  years_experience
0   16852973       HR                15
1   22323967       HR                 0
2   33176873       HR                20
3   27018550       HR                 0
4   17812897       HR                 0
5   11592605       HR                 0
6   25824789       HR                 0
7   15375009       HR                 0
8   11847784       HR                15
9   32896934       HR                 0
10  29149998       HR                 3
11  11480899       HR                 0
12  23155093       HR                 0
13  11763983       HR                 0
14  27490876       HR                 0
15  32977530       HR                 0
16  93002334       HR                 0
17  24184357       HR                 0
18  73077810       HR                 0
19  13879043       HR                 7

In [10]:
df["years_experience"].describe()

count    2481.000000
mean        2.262797
std         5.836228
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max        44.000000
Name: years_experience, dtype: float64

In [11]:
experience_check = df[
    df["years_experience"] > 0
][
    ["ID", "Category", "years_experience", "clean_resume"]
]

experience_check[
    ["ID", "Category", "years_experience"]
].head(20)

           ID  Category  years_experience
0    16852973        HR                15
2    33176873        HR                20
8    11847784        HR                15
10   29149998        HR                 3
19   13879043        HR                 7
21   18827609        HR                 3
22   25676643        HR                 9
28   18334783        HR                20
38   51769822        HR                30
46   34554248        HR                 3
51   39650734        HR                 5
52   72231872        HR                 9
53   13520837        HR                 5
55   30862904        HR                10
59   27523575        HR                 6
65   17412079        HR                 7
73   23408537        HR                10
81   24508725        HR                 6
85   34740556        HR                 8
110  37058472  DESIGNER                15

In [12]:
print(
    experience_check["clean_resume"].iloc[0]
)

hr administrator marketing associate hr administrator summary dedicated customer service manager with 15  years of experience in hospitality and customer service management  respected builder and leader of customer focused teams  strives to instill a shared  enthusiastic commitment to customer service  highlights focused on customer satisfaction team management marketing savvy conflict resolution techniques training and development skilled multi tasker client relations specialist accomplishments missouri dot supervisor training certification certified by ihg in customer loyalty and marketing by segment hilton worldwide general manager training certification accomplished trainer for cross server hospitality systems such as hilton onq   micros opera pms   fidelio opera reservation system  ors    holidex completed courses and seminars in customer service  sales strategies  inventory control  loss prevention  safety  time management  leadership and performance assessment  experience hr administrator marketing associate hr administrator dec 2013 to current company name   city   state helps to develop policies  directs and coordinates activities such as employment  compensation  labor relations  benefits  training  and employee services  prepares employee separation notices and related documentation keeps records of benefits plans participation such as insurance and pension plan  personnel transactions such as hires  promotions  transfers  performance reviews  and terminations  and employee statistics for government reporting  advises management in appropriate resolution of employee relations issues  administers benefits programs such as life  health  dental  insurance  pension plans  vacation  sick leave  leave of absence  and employee assistance  marketing associate designed and created marketing collateral for sales meetings  trade shows and company executives  managed the in house advertising program consisting of print and media collateral pieces  assisted in the complete design and launch of the company s website in 2 months  created an official company page on facebook to facilitate interaction with customers  analyzed ratings and programming features of competitors to evaluate the effectiveness of marketing strategies  advanced medical claims analyst mar 2012 to dec 2013 company name   city   state reviewed medical bills for the accuracy of the treatments  tests  and hospital stays prior to sanctioning the claims  trained to interpret the codes  icd 9  cpt  and terminology commonly used in medical billing to fully understand the paperwork that is submitted by healthcare providers  required to have organizational and analytical skills as well as computer skills  knowledge of medical terminology and procedures  statistics  billing standards  data analysis and laws regarding medical billing  assistant general manager jun 2010 to dec 2010 company name   city   state performed duties including but not limited to  budgeting and financial management  accounting  human resources  payroll and purchasing  established and maintained close working relationships with all departments of the hotel to ensure maximum operation  productivity  morale and guest service  handled daily operations and reported directly to the corporate office  hired and trained staff on overall objectives and goals with an emphasis on high customer service  marketing and advertising  working on public relations with the media  government and local businesses and chamber of commerce  executive support   marketing assistant jul 2007 to jun 2010 company name   city   state provided assistance to various department heads   executive  marketing  customer service  human resources  managed front end operations to ensure friendly and efficient transactions  ensured the swift resolution of customer issues to preserve customer loyalty while complying with company policies  exemplified the second to none customer service delivery in all interactions with customers and potential clients  reservation   front office manager jun 2004 to jul 2007 company name   city   state owner  partner dec 2001 to may 2004 company name   city   state price integrity coordinator aug 1999 to dec 2001 company name   city   state education n a   business administration 1999 jefferson college   city   state business administration marketing   advertising high school diploma   college prep  studies 1998 sainte genevieve senior high   city   state awarded american shrubel leadership scholarship to jefferson college skills accounting  ads  advertising  analytical skills  benefits  billing  budgeting  clients  customer service  data analysis  delivery  documentation  employee relations  financial management  government relations  human resources  insurance  labor relations  layout  marketing  marketing collateral  medical billing  medical terminology  office  organizational  payroll  performance reviews  personnel  policies  posters  presentations  public relations  purchasing  reporting  statistics  website

In [13]:
high_experience = df[
    df["years_experience"] > 15
][
    ["ID", "Category", "years_experience", "clean_resume"]
]

high_experience[
    ["ID", "Category", "years_experience"]
]

            ID  Category  years_experience
2     33176873        HR                20
28    18334783        HR                20
38    51769822        HR                30
121   36269672  DESIGNER                44
122   90066849  DESIGNER                28
...        ...       ...               ...
2418  10945968  AVIATION                20
2449  19284293  AVIATION                20
2450  11752500  AVIATION                20
2466  49646155  AVIATION                17
2473  25625173  AVIATION                25

[123 rows x 3 columns]

In [14]:
print(high_experience["clean_resume"].iloc[0])

hr director summary over 20 years experience in recruiting  15 plus years in human resources executive management  5 years of hris development and maintenance 4 years working in a healthcare enviroment skills recruiting fmla eeo flsa hris development benefit administration policy development web page development accomplishments kansas health institute  health outcomes for the state of kansas  1999 memberships and accolades  project management institute member  shrm  chamber of commerce  1999 friends university president s honor roll  1997 friends university dean s honor roll  student liaison for friends university topeka  member of mother to mother  member of the topeka advertising federation  several production pieces created nominated for addy awards  received recognition for outstanding customer service assistance by the state of kansas travel and tourism department   ashhra  kahhr  acm  additional information  leading change  i have been instrumental in development and implementation of the adjutant general s retention research project  involving survey development and analyzing the results of the surveys to present to the adjutant general to help retain the qualified talent of the departments  i have been tasked with working with the federal security manager for the joint forces headquarters in developing policies  procedures and processes to ensure that all current and new state employees have the appropriate security clearances for the position held per the federal government requirements  while at lmis  i lead the job vacancy project and was able to produce results in less time and man hours than in years before with staff that were inexperienced in the jvc process and procedures  i have been responsible to develop  plan and implement database programs  for the last three positions i have held  these were designed to cultivate  involve  renew contact  and promote active and potential employees  these databases were used for reporting fte usage  budget management and turnover reports  while working in the healthcare field  i took the initiative in creating a local website that was used to receive and respond to requests for information and assistance in marketing and promoting the healthcare facility along with recruitment of potential employees  as human resource coordinator in the healthcare field  i managed the front office personnel  reduced contract labor costs for nursing staff and implemented a unique pay structure to increase prn staff utilization  i continually think  outside the box  to create and develop strategies to resolve issues faced in my work environment  in my current position  i have met and exceeded all hiring goals for the firm  this resulted in our client increasing the business transferred to our location  experience hr director 09 2016 to current company name city   state developed new website for agency  payroll processing changes  and implementation of new hris system  oversaw the employment process taking the lead role in clinician  physician and management team recruitment initiatives  developed  maintain and interpret hr policy  authored the employee handbook  provided coaching and support to management and supervisors on performance management and other related issues  maintained in depth knowledge of legal requirements related to day to day management of employees  reducing legal risks and ensuring regulatory compliance  evaluated and recommend changes to the employee benefits plan  oversaw day to day administration of benefits  hr director 04 2009 to 09 2016 company name city   state develped supervisory education  shro website  shro hris system and automation of payroll processing  established and directed a comprehensive statewide human resource program for both classified and unclassified state employees positions in the adjutant general s department  resolved non routine hr related issues associated as they arose  reviewed documents and approved all hires and promotions  reviews and approved  modified and or disapproved wage salary requests to hire individuals above the pre established minimum classified or unclassified pay rate  reviewed any significant changes to position descriptions and determined if reclassification should be pursued  reviewed position descriptions for new positions and determined the appropriate wage range based on comparable classified position  if they exist   consulted with the tag and both military and state manager  supervisors in order to provide technical and common sense guidance on properly addressing sensitive or complex employee and organizational issues  aided them in achieving their ever changing program goals and provided innovative ideas for staffing  served as the administration s management representative in labor negotiations with the local kape unit at the 190th fire department  hr manager sr  recruiter 10 2003 to 06 2006 company name city   state created an hris tracking system used for recruitment  responsible for ramp up and hiring of all customer service agents  and other positions as needed  placement and development of all advertising met and exceeded all hiring goals  responsible for hiring senior management to cover such duties as  team managers  payroll  quality control  responsible for recruitment of 950 new employees  meeting and exceeded goals set  coordinated and facilitated manpower planning  recruitment and retention  career development and training  staff relations  compensation and benefits  compliance with local  state and federal statutory regulations  public programs  and regulatory audit procedures  served as a resource person to administration  mid level management and staff regarding hr related  human resources coordinator 03 1996 to 02 2000 company name city   state developed hris database from ground up for employee records and monitoring  instrumental in reducing the use of agency staffing needs for hospital  coordinated and facilitates manpower planning  recruitment and retention  career development and training  staff relations  compensation and benefits  compliance with local  state and federal statutory regulations  public programs  and regulatory audit procedures  served as the hr resource source for administration  mid level management and staff  coordinated hiring procedures  appraisals  pay increases  promotions  transfers  terminations  job postings  and all corrective actions  one person office  responsible for all osha  work comp  benefits  payroll  etc  education and training master s degree   information management systems 05 2005 friends university city   state   united states 3 5 credits earned  62 semester hours information management systems bachelor of science   organizational management 05 2000 friends university city   state   united states 4 0 credits earned  62 semester hours activities and honors topeka chamber of commerce  ambassador kansas hospital association  health care human resources member shrm  legislative liaison skills desktop publishing  newsletter productions  database management  leadership training  osha  fmla  workers compensation  pagemaker  agency automation  back up  benefits  budget management  corel suite  harvard graphics  access  excel  microsoft publisher  ms word  quark express  quattro pro  strategic planning  web page development  wordperfect

In [15]:
zero_experience = df[
    df["years_experience"] == 0
]

print(zero_experience[
    ["ID", "Category", "clean_resume"]
].head(5).to_string())

         ID Category                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           clean_resume
1  22323967       HR                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  hr specialist  us hr operations summary versatile media professional with background in communications  marketing  human resources and technology  experience 09 2015 to current hr specialist  us hr operations company name   city   state managed communication regarding launch of operations group  policy changes and system outages designed standard work and job aids to create comprehensive training program for new employees and contractors audited job postings for old  pending  on hold and draft positions  audited union hourly  non union hourly and salary background checks and drug screens conducted monthly new hire benefits briefing to new employees across all business units served as a link between hr managers and vendors by handling questions and resolving system related issues provide real time process improvement feedback on key metrics and initiatives successfully re branded us hr operations sharepoint site business unit project manager for rfi rfp on background check and drug screen vendor 01 2014 to 05 2015 it  marketing and communications co op company name   city   state posted new articles  changes and updates to corporate sharepoint site including graphics and visual communications  researched and drafted articles and feature stories to promote company activities and programs  co edited and developed content for quarterly published newsletter  provided communication support for internal and external events  collaborated with communication team  media professionals and vendors to determine program needs for print materials  web design and digital communications  entrusted to lead product  service and software launches for digital asset management tool  marketing toolkit website and executive tradeshows calendar  created presentations for management and executive approval to ensure alignment with corporate guidelines and branding  maintained the mysikorsky sharepoint site and provided timely solutions to mitigate issues  created story board and produced video for annual it all hands meeting  10 2012 to 01 2014 relationship coordinator marketing specialist company name   city   state partnered with vendor to manage the in house advertising program consisting of print and media collateral pieces  coordinated pre show and post show activities at trade shows  managed marketing campaigns to generate new business and to support partner and sales teams  ordered marketing collateral for meetings  trade shows and advisors  improved  administered and modified marketing programs to increase product awareness  assisted in preparing internal promotional publications  managed marketing material inventory and supervised distribution of publications to ensure high quality product output  coordinated marketing materials including brochures  promotional materials and products  partnered with graphic designers to develop appropriate materials and branding for brochures  used tracking and reporting systems for sales leads and appointments  09 2009 to 10 2012 assistant head teller company name   city   state received an internal audit score of 100    performed daily and monthly audits of atm machines and tellers  educated customers on a variety of retail products and available credit options  consistently met or exceeded quarterly sales goals promoted products and services to customers while maintaining company brand identity   implemented programs to achieve and exceed customer and company participation goals organized company sponsored events on campus resulting in increased brand awareness   coached peers on the proper use of programs to improve work flow efficiency utilized product knowledge to successfully sell to and refer clients based on individual needs promoted marketing the grand opening of new branch locations to strengthen company brand affinity   organized company sponsored events resulting in increased brand awareness and improved sales   coached peers on the proper use of programs to increase work flow efficiency senior producer   2014 shu media exchange company name   city   state planned and executed event focusing on connecticut s creative corridor  growth of industry and opportunities that come with development  a panel of industry professionals addressed topics related to media and hosted a question and answer session for approximately 110 attendees  following the forum  guests were invited to engage in networking and conversation at a post event reception  education 2014 master of arts   corporate communication   public relations sacred heart university   city   state 2013 bachelor of arts   relational communication western connecticut state university   city   state skills adobe photoshop  adp  asset management  branding  brochures  content  customer care  final cut pro  graphics  graphic  hr  illustrator  indesign  innovation  inventory  lotus notes  marketing  marketing materials  marketing material  materials  microsoft office  sharepoint  newsletter  presentations  process improvement  project management  promotional materials  publications  quality  real time  recruitment  reporting  rfp  sales  stories  employee development  video  web design  website  articles

In [16]:
import re

In [17]:
def extract_date_ranges(text):
    pattern = r'(\d{1,2})\s+(\d{4})\s+to\s+(current|\d{1,2}\s+\d{4})'

    matches = re.findall(pattern, text.lower())

    return matches

In [18]:
text = df.loc[
    df["ID"] == 22323967,
    "clean_resume"
].iloc[0]

print(extract_date_ranges(text))

[('09', '2015', 'current'), ('01', '2014', '05 2015'), ('10', '2012', '01 2014'), ('09', '2009', '10 2012')]

In [19]:
from datetime import datetime

In [20]:
def calculate_duration(start_month, start_year, end_value):
    
    start_date = datetime(
        int(start_year),
        int(start_month),
        1
    )

    if end_value == "current":
        end_date = datetime.now()
    else:
        end_month, end_year = end_value.split()
        
        end_date = datetime(
            int(end_year),
            int(end_month),
            1
        )

    months = (
        (end_date.year - start_date.year) * 12
        + (end_date.month - start_date.month)
    )

    return months

In [21]:
print(
    calculate_duration(
        "09",
        "2015",
        "current"
    )
)

132

In [29]:
def calculate_total_experience(text):
    
    date_ranges = extract_date_ranges(text)
    
    periods = []
    
    current_date = datetime.now()
    
    for start_month, start_year, end_value in date_ranges:
        
        start_date = datetime(
            int(start_year),
            int(start_month),
            1
        )
        
        if end_value == "current":
            end_date = current_date
        else:
            end_month, end_year = end_value.split()
            
            end_date = datetime(
                int(end_year),
                int(end_month),
                1
            )
        
        if end_date >= start_date:
            periods.append(
                (start_date, end_date)
            )
    
    if not periods:
        return 0.0
    
    # Sort by starting date
    periods.sort(key=lambda x: x[0])
    
    # Merge overlapping periods
    merged_periods = [periods[0]]
    
    for start, end in periods[1:]:
        
        last_start, last_end = merged_periods[-1]
        
        if start <= last_end:
            
            if end > last_end:
                merged_periods[-1] = (
                    last_start,
                    end
                )
        
        else:
            merged_periods.append(
                (start, end)
            )
    
    total_months = 0
    
    for start, end in merged_periods:
        
        months = (
            (end.year - start.year) * 12
            + (end.month - start.month)
        )
        
        total_months += months
    
    return round(total_months / 12, 1)

In [23]:
text = df.loc[
    df["ID"] == 22323967,
    "clean_resume"
].iloc[0]

print(calculate_total_experience(text))

16.7

In [24]:
df["calculated_experience"] = df["clean_resume"].apply(
    calculate_total_experience
)

In [25]:
df[
    ["ID", "Category", "years_experience", "calculated_experience"]
].head(20)

          ID Category  years_experience  calculated_experience
0   16852973       HR                15                    0.0
1   22323967       HR                 0                   16.7
2   33176873       HR                20                   24.0
3   27018550       HR                 0                    0.0
4   17812897       HR                 0                    0.0
5   11592605       HR                 0                   22.8
6   25824789       HR                 0                   33.7
7   15375009       HR                 0                   17.4
8   11847784       HR                15                   19.2
9   32896934       HR                 0                   41.6
10  29149998       HR                 3                   20.2
11  11480899       HR                 0                   22.8
12  23155093       HR                 0                   26.2
13  11763983       HR                 0                    0.0
14  27490876       HR                 0                    0.0
15  32977530       HR                 0                   12.9
16  93002334       HR                 0                    0.0
17  24184357       HR                 0                    0.0
18  73077810       HR                 0                    0.0
19  13879043       HR                 7                    6.4

In [26]:
df["calculated_experience"].describe()

count    2481.000000
mean       11.101814
std        14.588477
min         0.000000
25%         0.000000
50%         1.200000
75%        20.700000
max       157.300000
Name: calculated_experience, dtype: float64

In [27]:
comparison = df[
    ["ID", "years_experience", "calculated_experience"]
].copy()

comparison.head(20)

          ID  years_experience  calculated_experience
0   16852973                15                    0.0
1   22323967                 0                   16.7
2   33176873                20                   24.0
3   27018550                 0                    0.0
4   17812897                 0                    0.0
5   11592605                 0                   22.8
6   25824789                 0                   33.7
7   15375009                 0                   17.4
8   11847784                15                   19.2
9   32896934                 0                   41.6
10  29149998                 3                   20.2
11  11480899                 0                   22.8
12  23155093                 0                   26.2
13  11763983                 0                    0.0
14  27490876                 0                    0.0
15  32977530                 0                   12.9
16  93002334                 0                    0.0
17  24184357                 0                    0.0
18  73077810                 0                    0.0
19  13879043                 7                    6.4

In [28]:
comparison[
    comparison["years_experience"] != comparison["calculated_experience"]
].head(20)

          ID  years_experience  calculated_experience
0   16852973                15                    0.0
1   22323967                 0                   16.7
2   33176873                20                   24.0
5   11592605                 0                   22.8
6   25824789                 0                   33.7
7   15375009                 0                   17.4
8   11847784                15                   19.2
9   32896934                 0                   41.6
10  29149998                 3                   20.2
11  11480899                 0                   22.8
12  23155093                 0                   26.2
15  32977530                 0                   12.9
19  13879043                 7                    6.4
21  18827609                 3                    5.7
22  25676643                 9                   14.9
24  87968870                 0                   21.8
26  14225422                 0                   41.3
27  29297973                 0                   22.4
28  18334783                20                    0.0
31  18316239                 0                    7.1

In [30]:
df["calculated_experience"] = df["clean_resume"].apply(
    calculate_total_experience
)

In [31]:
df["calculated_experience"].describe()

count    2481.000000
mean        9.362152
std        11.431150
min         0.000000
25%         0.000000
50%         1.000000
75%        18.200000
max        51.100000
Name: calculated_experience, dtype: float64

In [32]:
df[
    ["ID", "Category", "calculated_experience"]
].sort_values(
    "calculated_experience",
    ascending=False
).head(20)

            ID                Category  calculated_experience
2014  39027764            CONSTRUCTION                   51.1
1996  12654876            CONSTRUCTION                   47.1
932   12341902             AGRICULTURE                   46.3
1153  20176584              CONSULTANT                   46.1
1327  15790602              AUTOMOBILE                   45.3
1811  33527446              ACCOUNTANT                   44.7
687   18365443              HEALTHCARE                   43.7
1095  16280971                   SALES                   43.2
1568  39295103                 FINANCE                   43.0
293   18159866  INFORMATION-TECHNOLOGY                   42.7
1135  30083884              CONSULTANT                   42.7
2133  23631724        PUBLIC-RELATIONS                   42.6
1994  27243670            CONSTRUCTION                   41.9
2143  21663616        PUBLIC-RELATIONS                   41.7
9     32896934                      HR                   41.6
26    14225422                      HR                   41.3
434   20478831                 TEACHER                   41.2
2185  11637468                 BANKING                   41.1
181   32532982                DESIGNER                   40.9
1017  26994282                   SALES                   40.7

In [33]:
df[
    ["ID", "Category", "calculated_experience"]
].head(20)

          ID Category  calculated_experience
0   16852973       HR                    0.0
1   22323967       HR                   16.7
2   33176873       HR                   24.0
3   27018550       HR                    0.0
4   17812897       HR                    0.0
5   11592605       HR                   14.2
6   25824789       HR                   33.7
7   15375009       HR                   17.3
8   11847784       HR                   19.0
9   32896934       HR                   41.6
10  29149998       HR                   20.2
11  11480899       HR                   22.8
12  23155093       HR                   26.2
13  11763983       HR                    0.0
14  27490876       HR                    0.0
15  32977530       HR                   12.6
16  93002334       HR                    0.0
17  24184357       HR                    0.0
18  73077810       HR                    0.0
19  13879043       HR                    6.4

In [34]:
top_experience = df[
    ["ID", "Category", "calculated_experience", "clean_resume"]
].sort_values(
    "calculated_experience",
    ascending=False
)

top_experience[
    ["ID", "Category", "calculated_experience"]
].head(20)

            ID                Category  calculated_experience
2014  39027764            CONSTRUCTION                   51.1
1996  12654876            CONSTRUCTION                   47.1
932   12341902             AGRICULTURE                   46.3
1153  20176584              CONSULTANT                   46.1
1327  15790602              AUTOMOBILE                   45.3
1811  33527446              ACCOUNTANT                   44.7
687   18365443              HEALTHCARE                   43.7
1095  16280971                   SALES                   43.2
1568  39295103                 FINANCE                   43.0
293   18159866  INFORMATION-TECHNOLOGY                   42.7
1135  30083884              CONSULTANT                   42.7
2133  23631724        PUBLIC-RELATIONS                   42.6
1994  27243670            CONSTRUCTION                   41.9
2143  21663616        PUBLIC-RELATIONS                   41.7
9     32896934                      HR                   41.6
26    14225422                      HR                   41.3
434   20478831                 TEACHER                   41.2
2185  11637468                 BANKING                   41.1
181   32532982                DESIGNER                   40.9
1017  26994282                   SALES                   40.7

In [35]:
print(top_experience["clean_resume"].iloc[0])

director of development professional summary real estate   development   construction executive versatile executive with 38 years experience in the real estate and construction industries possessing a combination of hands on technical experience coupled with strong organizational and leadership skills to manage project teams from concept to completion  honest and thoughtful style results in loyal teams that work toward a common goal  strategic thinker and planner with analytical skills and proven aptitude to manage complex and numerous projects and coordinate the efforts of corporate departments  landlords  designers  consultants  and contractors to turn over successful projects  honest and pragmatic approach to conflict resolution and problem solving  immense pursuit and tireless effort to produce successful and timely results  strong real estate aptitude allows for thorough due diligence and market analysis  for contract  purchase and lease administration  commercial and residential project management   development   estimating   budget preparation and implementation   profit   loss responsibility   value engineering   cost control   team building   employee training   site selection    land use entitlement   permitting   design and plan review   bidding and negotiation   purchase and lease negotiation   purchase  lease and contract administration construction manager familiar with preparing and negotiating contracts with clients and suppliers  innovative construction manager adept at finding engaging ways to motivate construction teams to exceed expectations and maintain high standards  skills work history 05 1999 to current director of development company name   city   state management of multiple projects in georgia and florida ranging to 3 4 million square feet annually management of construction of high end health club facilities ranging to  10 million each management of a remote corporate office  including budgets ranging to  60 million  5 employees management of construction managers  designers  consultants  contractors  landlords site analysis  purchase and lease negotiation due diligence  entitlement processing  permitting reporting to corporate office and departments  project schedules  progress and coordination of ff e led the company for projects completed and cost control initiated the interior and exterior branding graphics  reviewed plans and specs during the schematic design of pre construction  coordinated utility service providers according to project schedules  obtained building and specialty permits from local jurisdictional agencies  conducted weekly production and operations contractor meetings  which facilitated stronger communication and the ability to resolve critical issues  performed regular job site observations to provide direction for all general contractor personnel  conducted all critical pre installation conferences with general contractors  subcontractors  consultants and manufacturer s representatives  digitally archived weekly progress and technical  knowledge base  photographs of all assigned projects  assisted the operations group with warranty service repairs  06 1996 to 05 1999 construction manager company name   city   state management of multiple motel projects throughout the united states  ranging to  4 million management of 4 construction managers in field operations management of construction training seminars for employees  designers and contractors site evaluation  coordination of design  permitting  budgets  negotiation with contractors reporting to corporate office and departments  project schedules  progress and coordination of ff e  reviewed plans and specs during the schematic design of pre construction  coordinated utility service providers according to project schedules  obtained building and specialty permits from local jurisdictional agencies  12 1992 to 06 1996 construction manager company name   city   state management of landlords and general contractors in the construction of approximately 45 retail stores per year throughout the southeastern united states  reporting to corporate office and departments  project schedules  progress and coordination of ff e  coordinate with marketing  merchandising and turnover to operations  reviewed plans and specs during the schematic design of pre construction  conducted weekly production and operations contractor meetings  which facilitated stronger communication and the ability to resolve critical issues  performed regular job site observations to provide direction for all general contractor personnel  conducted all critical pre installation conferences with general contractors  subcontractors  consultants and manufacturer s representatives  oversaw the entire building turnover process  while enhancing communication between all construction management  conducted routine quality audits to ensure that work was progressing per the specifications and initiated corrective actions  02 1989 to 12 1992 construction superintendent company name   city   state supervised construction and remodel of retail and restaurant projects  ranging  200 thousand    4 million  design craft properties  02 1986 to 02 1989 owner developer company name   city   state full responsibilities of operating a single family home building company  successfully completed the development of two multi unit subdivisions and over 100 single family homes  06 1983 to 02 1986 construction superintendent company name   city   state managed construction and turnover of single family custom homes  managed construction of commercial office facilities  10 1980 to 06 1983 carpenter   foreman company name   city   state carpenter and carpenter foreman on heavy industrial projects in wyoming  tennessee and south carolina  08 1975 to 10 1980 draftsman   field service supervisor company name   city   state design and drafting of air structures and dome roofs  field service to owners in the assembly and erection of air structures and dome roofs  education 5 1975 bs   building construction design and technology eastern kentucky university   city   state building construction design and technology building construction trades certificate skills assembly  branding  budgets  carpenter  cost control  drafting  due diligence  graphics  marketing  merchandising  office  negotiation  operations management  progress  reporting  retail  seminars

In [36]:
print(
    "Above 30 years:",
    (df["calculated_experience"] > 30).sum()
)

print(
    "Above 40 years:",
    (df["calculated_experience"] > 40).sum()
)

print(
    "Above 50 years:",
    (df["calculated_experience"] > 50).sum()
)

Above 30 years: 134
Above 40 years: 25
Above 50 years: 1

In [37]:
median_experience = df[
    ["ID", "Category", "calculated_experience"]
].sort_values(
    "calculated_experience"
)

median_experience.iloc[
    len(median_experience) // 2
]

ID                       38860712
Category                 ADVOCATE
calculated_experience         1.0
Name: 457, dtype: object

In [38]:
candidate = df[
    df["ID"] == 39027764
]

print(candidate["clean_resume"].iloc[0])

director of development professional summary real estate   development   construction executive versatile executive with 38 years experience in the real estate and construction industries possessing a combination of hands on technical experience coupled with strong organizational and leadership skills to manage project teams from concept to completion  honest and thoughtful style results in loyal teams that work toward a common goal  strategic thinker and planner with analytical skills and proven aptitude to manage complex and numerous projects and coordinate the efforts of corporate departments  landlords  designers  consultants  and contractors to turn over successful projects  honest and pragmatic approach to conflict resolution and problem solving  immense pursuit and tireless effort to produce successful and timely results  strong real estate aptitude allows for thorough due diligence and market analysis  for contract  purchase and lease administration  commercial and residential project management   development   estimating   budget preparation and implementation   profit   loss responsibility   value engineering   cost control   team building   employee training   site selection    land use entitlement   permitting   design and plan review   bidding and negotiation   purchase and lease negotiation   purchase  lease and contract administration construction manager familiar with preparing and negotiating contracts with clients and suppliers  innovative construction manager adept at finding engaging ways to motivate construction teams to exceed expectations and maintain high standards  skills work history 05 1999 to current director of development company name   city   state management of multiple projects in georgia and florida ranging to 3 4 million square feet annually management of construction of high end health club facilities ranging to  10 million each management of a remote corporate office  including budgets ranging to  60 million  5 employees management of construction managers  designers  consultants  contractors  landlords site analysis  purchase and lease negotiation due diligence  entitlement processing  permitting reporting to corporate office and departments  project schedules  progress and coordination of ff e led the company for projects completed and cost control initiated the interior and exterior branding graphics  reviewed plans and specs during the schematic design of pre construction  coordinated utility service providers according to project schedules  obtained building and specialty permits from local jurisdictional agencies  conducted weekly production and operations contractor meetings  which facilitated stronger communication and the ability to resolve critical issues  performed regular job site observations to provide direction for all general contractor personnel  conducted all critical pre installation conferences with general contractors  subcontractors  consultants and manufacturer s representatives  digitally archived weekly progress and technical  knowledge base  photographs of all assigned projects  assisted the operations group with warranty service repairs  06 1996 to 05 1999 construction manager company name   city   state management of multiple motel projects throughout the united states  ranging to  4 million management of 4 construction managers in field operations management of construction training seminars for employees  designers and contractors site evaluation  coordination of design  permitting  budgets  negotiation with contractors reporting to corporate office and departments  project schedules  progress and coordination of ff e  reviewed plans and specs during the schematic design of pre construction  coordinated utility service providers according to project schedules  obtained building and specialty permits from local jurisdictional agencies  12 1992 to 06 1996 construction manager company name   city   state management of landlords and general contractors in the construction of approximately 45 retail stores per year throughout the southeastern united states  reporting to corporate office and departments  project schedules  progress and coordination of ff e  coordinate with marketing  merchandising and turnover to operations  reviewed plans and specs during the schematic design of pre construction  conducted weekly production and operations contractor meetings  which facilitated stronger communication and the ability to resolve critical issues  performed regular job site observations to provide direction for all general contractor personnel  conducted all critical pre installation conferences with general contractors  subcontractors  consultants and manufacturer s representatives  oversaw the entire building turnover process  while enhancing communication between all construction management  conducted routine quality audits to ensure that work was progressing per the specifications and initiated corrective actions  02 1989 to 12 1992 construction superintendent company name   city   state supervised construction and remodel of retail and restaurant projects  ranging  200 thousand    4 million  design craft properties  02 1986 to 02 1989 owner developer company name   city   state full responsibilities of operating a single family home building company  successfully completed the development of two multi unit subdivisions and over 100 single family homes  06 1983 to 02 1986 construction superintendent company name   city   state managed construction and turnover of single family custom homes  managed construction of commercial office facilities  10 1980 to 06 1983 carpenter   foreman company name   city   state carpenter and carpenter foreman on heavy industrial projects in wyoming  tennessee and south carolina  08 1975 to 10 1980 draftsman   field service supervisor company name   city   state design and drafting of air structures and dome roofs  field service to owners in the assembly and erection of air structures and dome roofs  education 5 1975 bs   building construction design and technology eastern kentucky university   city   state building construction design and technology building construction trades certificate skills assembly  branding  budgets  carpenter  cost control  drafting  due diligence  graphics  marketing  merchandising  office  negotiation  operations management  progress  reporting  retail  seminars

In [39]:
high_experience = df[
    df["calculated_experience"] > 40
][
    ["ID", "Category", "calculated_experience"]
].sort_values(
    "calculated_experience",
    ascending=False
)

high_experience

            ID                Category  calculated_experience
2014  39027764            CONSTRUCTION                   51.1
1996  12654876            CONSTRUCTION                   47.1
932   12341902             AGRICULTURE                   46.3
1153  20176584              CONSULTANT                   46.1
1327  15790602              AUTOMOBILE                   45.3
1811  33527446              ACCOUNTANT                   44.7
687   18365443              HEALTHCARE                   43.7
1095  16280971                   SALES                   43.2
1568  39295103                 FINANCE                   43.0
293   18159866  INFORMATION-TECHNOLOGY                   42.7
1135  30083884              CONSULTANT                   42.7
2133  23631724        PUBLIC-RELATIONS                   42.6
1994  27243670            CONSTRUCTION                   41.9
2143  21663616        PUBLIC-RELATIONS                   41.7
9     32896934                      HR                   41.6
26    14225422                      HR                   41.3
434   20478831                 TEACHER                   41.2
2185  11637468                 BANKING                   41.1
181   32532982                DESIGNER                   40.9
1397  91591026                    CHEF                   40.7
1017  26994282                   SALES                   40.7
997   30083943                   SALES                   40.4
1130  15281412              CONSULTANT                   40.4
422   27126818                 TEACHER                   40.2
901   14107571                 FITNESS                   40.1

In [40]:
for _, row in high_experience.head(10).iterrows():
    
    print("=" * 80)
    print("ID:", row["ID"])
    print("Category:", row["Category"])
    print("Experience:", row["calculated_experience"])
    
    ranges = extract_date_ranges(
        df.loc[
            df["ID"] == row["ID"],
            "clean_resume"
        ].iloc[0]
    )
    
    print("Date ranges:")
    for r in ranges:
        print(r)

================================================================================
ID: 39027764
Category: CONSTRUCTION
Experience: 51.1
Date ranges:
('05', '1999', 'current')
('06', '1996', '05 1999')
('12', '1992', '06 1996')
('02', '1989', '12 1992')
('02', '1986', '02 1989')
('06', '1983', '02 1986')
('10', '1980', '06 1983')
('08', '1975', '10 1980')
================================================================================
ID: 12654876
Category: CONSTRUCTION
Experience: 47.1
Date ranges:
('08', '2015', 'current')
('01', '2012', '01 2015')
('01', '2012', '01 2015')
('01', '2007', '01 2008')
('01', '1998', '01 1999')
('01', '1994', '01 2012')
('01', '1990', '01 1994')
('01', '1986', '01 1990')
('01', '1983', '01 1986')
('01', '1979', '01 1983')
================================================================================
ID: 12341902
Category: AGRICULTURE
Experience: 46.3
Date ranges:
('10', '2007', 'current')
('08', '1999', '03 2015')
('03', '1982', '06 1999')
('01', '1975', '01 1977')
================================================================================
ID: 20176584
Category: CONSULTANT
Experience: 46.1
Date ranges:
('02', '2014', 'current')
('08', '2013', '12 2013')
('01', '2012', '08 2013')
('11', '2010', '11 2011')
('01', '2010', '03 2010')
('01', '2004', '10 2009')
('07', '2002', '10 2003')
('04', '2000', '05 2002')
('08', '1997', '01 2000')
('04', '1993', '07 1997')
('01', '1990', '04 1993')
('06', '1978', '11 1989')
================================================================================
ID: 15790602
Category: AUTOMOBILE
Experience: 45.3
Date ranges:
('02', '1999', 'current')
('09', '1997', '02 1999')
('04', '1996', '09 1997')
('07', '1991', '03 1996')
('07', '1990', '06 1991')
('10', '1986', '06 1990')
('01', '1984', '09 1986')
('01', '1981', '01 1984')
================================================================================
ID: 33527446
Category: ACCOUNTANT
Experience: 44.7
Date ranges:
('01', '2009', '02 2010')
('01', '1993', 'current')
('01', '1991', '01 1992')
('01', '1981', '01 1990')
('01', '1980', '01 1981')
================================================================================
ID: 18365443
Category: HEALTHCARE
Experience: 43.7
Date ranges:
('01', '1997', 'current')
('01', '1993', '01 1996')
('01', '1983', 'current')
================================================================================
ID: 16280971
Category: SALES
Experience: 43.2
Date ranges:
('05', '2017', '04 1993')
('12', '1998', 'current')
('04', '1993', '12 1998')
('07', '1983', 'current')
================================================================================
ID: 39295103
Category: FINANCE
Experience: 43.0
Date ranges:
('11', '2005', '11 2017')
('07', '1996', '02 2005')
('03', '1990', '05 1995')
('11', '1979', '06 1985')
('06', '1985', '11 1989')
('07', '1972', '10 1979')
================================================================================
ID: 18159866
Category: INFORMATION-TECHNOLOGY
Experience: 42.7
Date ranges:
('06', '2004', 'current')
('01', '2002', '06 2004')
('01', '1995', '01 2002')
('01', '1993', '01 1995')
('01', '1990', '01 1993')
('01', '1985', '01 1990')
('01', '1984', '01 1985')

In [41]:
required_experience = 3

def calculate_experience_score(experience, required):
    
    if required <= 0:
        return 0
    
    score = (experience / required) * 100
    
    return min(score, 100)

In [42]:
df["experience_score"] = df[
    "calculated_experience"
].apply(
    lambda x: calculate_experience_score(
        x,
        required_experience
    )
)

In [43]:
df[
    [
        "ID",
        "Category",
        "calculated_experience",
        "experience_score"
    ]
].sort_values(
    "experience_score",
    ascending=False
).head(20)

            ID  Category  calculated_experience  experience_score
1     22323967        HR                   16.7             100.0
2466  49646155  AVIATION                   23.6             100.0
2467  33627938  AVIATION                   17.2             100.0
2471  17008356  AVIATION                    9.2             100.0
2475  17655479  AVIATION                   26.2             100.0
2476  12043694  AVIATION                   11.7             100.0
2478  24589765  AVIATION                   28.1             100.0
19    13879043        HR                    6.4             100.0
22    25676643        HR                   14.9             100.0
24    87968870        HR                   21.8             100.0
26    14225422        HR                   41.3             100.0
27    29297973        HR                   22.4             100.0
31    18316239        HR                    7.1             100.0
32    17855844        HR                   25.1             100.0
2434  17686472  AVIATION                   10.0             100.0
2435  54232810  AVIATION                   15.2             100.0
2437  68216398  AVIATION                   18.3             100.0
2438  17983430  AVIATION                   19.0             100.0
2439  92283635  AVIATION                   14.8             100.0
2440  11614114  AVIATION                   12.0             100.0

In [44]:
df[
    [
        "ID",
        "Category",
        "calculated_experience",
        "experience_score"
    ]
].to_csv(
    "../data/processed/experience_results.csv",
    index=False
)