In [1]:
import pandas as pd

In [2]:
tfidf_results = pd.read_csv(
    "../data/processed/tfidf_matching_results.csv"
)

skill_results = pd.read_csv(
    "../data/processed/skill_matching_results.csv"
)

experience_results = pd.read_csv(
    "../data/processed/experience_results.csv"
)

print("TF-IDF:", tfidf_results.shape)
print("Skills:", skill_results.shape)
print("Experience:", experience_results.shape)

TF-IDF: (2481, 4)
Skills: (2481, 7)
Experience: (2481, 4)

In [3]:
print("TF-IDF duplicate IDs:",
      tfidf_results["ID"].duplicated().sum())

print("Skills duplicate IDs:",
      skill_results["ID"].duplicated().sum())

print("Experience duplicate IDs:",
      experience_results["ID"].duplicated().sum())

TF-IDF duplicate IDs: 0
Skills duplicate IDs: 0
Experience duplicate IDs: 0

In [4]:
combined_results = tfidf_results.merge(
    skill_results[
        [
            "ID",
            "matched_skills",
            "missing_skills",
            "skill_coverage"
        ]
    ],
    on="ID",
    how="inner"
)

print("After TF-IDF + Skills:", combined_results.shape)

After TF-IDF + Skills: (2481, 7)

In [5]:
combined_results = combined_results.merge(
    experience_results[
        [
            "ID",
            "calculated_experience",
            "experience_score"
        ]
    ],
    on="ID",
    how="inner"
)

print("Final merged shape:", combined_results.shape)

Final merged shape: (2481, 9)

In [6]:
print("Number of candidates:", len(combined_results))

print(
    "Duplicate IDs after merge:",
    combined_results["ID"].duplicated().sum()
)

print(
    "Missing experience scores:",
    combined_results["experience_score"].isna().sum()
)

Number of candidates: 2481
Duplicate IDs after merge: 0
Missing experience scores: 0

In [7]:
combined_results["overall_score"] = (
    0.30 * combined_results["match_score"]
    + 0.40 * combined_results["skill_coverage"]
    + 0.30 * combined_results["experience_score"]
)

In [8]:
combined_results = combined_results.sort_values(
    "overall_score",
    ascending=False
).reset_index(drop=True)

In [9]:
combined_results["overall_rank"] = range(
    1,
    len(combined_results) + 1
)

In [10]:
top_candidates = combined_results[
    [
        "overall_rank",
        "ID",
        "Category",
        "match_score",
        "skill_coverage",
        "experience_score",
        "overall_score",
        "matched_skills",
        "missing_skills"
    ]
].head(20)

top_candidates

,overall_rank,ID,Category,match_score,skill_coverage,experience_score,overall_score,matched_skills,missing_skills
0,1,62994611,AGRICULTURE,21.273043,71.428571,100.0,64.953341,"['python', 'sql', 'javascript', 'react', 'mong...","['fastapi', 'rest api']"
1,2,83816738,INFORMATION-TECHNOLOGY,13.492720,42.857143,100.0,51.190673,"['javascript', 'mongodb', 'react']","['python', 'sql', 'fastapi', 'rest api']"
2,3,95429627,CONSULTANT,7.737766,42.857143,100.0,49.464187,"['python', 'sql', 'javascript']","['fastapi', 'mongodb', 'rest api', 'react']"
3,4,42156237,DIGITAL-MEDIA,14.860788,28.571429,100.0,45.886808,"['python', 'javascript']","['fastapi', 'sql', 'react', 'rest api', 'mongo..."
4,5,27152464,ENGINEERING,12.698314,28.571429,100.0,45.238066,"['python', 'mongodb']","['fastapi', 'sql', 'javascript', 'react', 'res..."
5,6,11981094,ENGINEERING,12.215554,28.571429,100.0,45.093238,"['javascript', 'rest api']","['python', 'fastapi', 'sql', 'react', 'mongodb']"
6,7,12011623,ENGINEERING,11.583866,28.571429,100.0,44.903731,"['python', 'sql']","['fastapi', 'javascript', 'react', 'rest api',..."
7,8,30863060,CONSULTANT,10.892236,28.571429,100.0,44.696242,"['sql', 'javascript']","['python', 'fastapi', 'react', 'rest api', 'mo..."
8,9,98300955,HEALTHCARE,10.555917,28.571429,100.0,44.595347,"['sql', 'javascript']","['python', 'fastapi', 'react', 'rest api', 'mo..."
9,10,12635195,INFORMATION-TECHNOLOGY,10.289198,28.571429,100.0,44.515331,"['python', 'javascript']","['fastapi', 'sql', 'react', 'rest api', 'mongo..."
10,11,64468610,ENGINEERING,9.882046,28.571429,100.0,44.393185,"['javascript', 'rest api']","['python', 'fastapi', 'sql', 'react', 'mongodb']"
11,12,29524570,DESIGNER,9.799851,28.571429,100.0,44.368527,"['sql', 'react']","['python', 'fastapi', 'javascript', 'rest api'..."
12,13,39441617,CONSULTANT,8.860518,28.571429,100.0,44.086727,"['python', 'javascript']","['fastapi', 'sql', 'react', 'rest api', 'mongo..."
13,14,13405733,INFORMATION-TECHNOLOGY,7.959325,28.571429,100.0,43.816369,"['python', 'sql']","['fastapi', 'javascript', 'react', 'rest api',..."
14,15,11813872,AGRICULTURE,7.798178,28.571429,100.0,43.768025,"['python', 'sql']","['fastapi', 'javascript', 'react', 'rest api',..."
15,16,15281412,CONSULTANT,5.696919,28.571429,100.0,43.137647,"['sql', 'javascript']","['python', 'fastapi', 'react', 'rest api', 'mo..."
16,17,12085736,DIGITAL-MEDIA,5.510977,28.571429,100.0,43.081865,"['sql', 'javascript']","['python', 'fastapi', 'react', 'rest api', 'mo..."
17,18,18067556,INFORMATION-TECHNOLOGY,4.852494,28.571429,100.0,42.884320,"['python', 'sql']","['fastapi', 'javascript', 'react', 'rest api',..."
18,19,16877897,HR,4.157569,28.571429,100.0,42.675842,"['sql', 'javascript']","['python', 'fastapi', 'react', 'rest api', 'mo..."
19,20,44115326,ADVOCATE,3.645208,28.571429,100.0,42.522134,"['sql', 'react']","['python', 'fastapi', 'javascript', 'rest api'..."

In [11]:
combined_results["overall_rank"] = range(
    1,
    len(combined_results) + 1
)

In [12]:
combined_results[
    [
        "overall_rank",
        "ID",
        "Category",
        "match_score",
        "skill_coverage",
        "experience_score",
        "overall_score"
    ]
].head(20)

,overall_rank,ID,Category,match_score,skill_coverage,experience_score,overall_score
0,1,62994611,AGRICULTURE,21.273043,71.428571,100.0,64.953341
1,2,83816738,INFORMATION-TECHNOLOGY,13.492720,42.857143,100.0,51.190673
2,3,95429627,CONSULTANT,7.737766,42.857143,100.0,49.464187
3,4,42156237,DIGITAL-MEDIA,14.860788,28.571429,100.0,45.886808
4,5,27152464,ENGINEERING,12.698314,28.571429,100.0,45.238066
5,6,11981094,ENGINEERING,12.215554,28.571429,100.0,45.093238
6,7,12011623,ENGINEERING,11.583866,28.571429,100.0,44.903731
7,8,30863060,CONSULTANT,10.892236,28.571429,100.0,44.696242
8,9,98300955,HEALTHCARE,10.555917,28.571429,100.0,44.595347
9,10,12635195,INFORMATION-TECHNOLOGY,10.289198,28.571429,100.0,44.515331
10,11,64468610,ENGINEERING,9.882046,28.571429,100.0,44.393185
11,12,29524570,DESIGNER,9.799851,28.571429,100.0,44.368527
12,13,39441617,CONSULTANT,8.860518,28.571429,100.0,44.086727
13,14,13405733,INFORMATION-TECHNOLOGY,7.959325,28.571429,100.0,43.816369
14,15,11813872,AGRICULTURE,7.798178,28.571429,100.0,43.768025
15,16,15281412,CONSULTANT,5.696919,28.571429,100.0,43.137647
16,17,12085736,DIGITAL-MEDIA,5.510977,28.571429,100.0,43.081865
17,18,18067556,INFORMATION-TECHNOLOGY,4.852494,28.571429,100.0,42.884320
18,19,16877897,HR,4.157569,28.571429,100.0,42.675842
19,20,44115326,ADVOCATE,3.645208,28.571429,100.0,42.522134

In [13]:
print("TF-IDF score range:")
print(
    combined_results["match_score"].min(),
    combined_results["match_score"].max()
)

print("\nSkill coverage range:")
print(
    combined_results["skill_coverage"].min(),
    combined_results["skill_coverage"].max()
)

print("\nExperience score range:")
print(
    combined_results["experience_score"].min(),
    combined_results["experience_score"].max()
)

print("\nOverall score range:")
print(
    combined_results["overall_score"].min(),
    combined_results["overall_score"].max()
)

TF-IDF score range:
0.0 21.273042936510212

Skill coverage range:
0.0 71.42857142857143

Experience score range:
0.0 100.0

Overall score range:
0.0 64.95334145238164

In [14]:
print(
    combined_results[
        [
            "match_score",
            "skill_coverage",
            "experience_score",
            "overall_score"
        ]
    ].isna().sum()
)

match_score         0
skill_coverage      0
experience_score    0
overall_score       0
dtype: int64

In [15]:
combined_results[
    [
        "overall_rank",
        "ID",
        "Category",
        "match_score",
        "skill_coverage",
        "experience_score",
        "overall_score"
    ]
].head(10)

,overall_rank,ID,Category,match_score,skill_coverage,experience_score,overall_score
0,1,62994611,AGRICULTURE,21.273043,71.428571,100.0,64.953341
1,2,83816738,INFORMATION-TECHNOLOGY,13.492720,42.857143,100.0,51.190673
2,3,95429627,CONSULTANT,7.737766,42.857143,100.0,49.464187
3,4,42156237,DIGITAL-MEDIA,14.860788,28.571429,100.0,45.886808
4,5,27152464,ENGINEERING,12.698314,28.571429,100.0,45.238066
5,6,11981094,ENGINEERING,12.215554,28.571429,100.0,45.093238
6,7,12011623,ENGINEERING,11.583866,28.571429,100.0,44.903731
7,8,30863060,CONSULTANT,10.892236,28.571429,100.0,44.696242
8,9,98300955,HEALTHCARE,10.555917,28.571429,100.0,44.595347
9,10,12635195,INFORMATION-TECHNOLOGY,10.289198,28.571429,100.0,44.515331

In [16]:
final_results = combined_results[
    [
        "overall_rank",
        "ID",
        "Category",
        "match_score",
        "skill_coverage",
        "experience_score",
        "overall_score",
        "matched_skills",
        "missing_skills"
    ]
]

final_results.to_csv(
    "../data/processed/overall_candidate_ranking.csv",
    index=False
)

In [17]:
print("Final results saved successfully.")

print(
    final_results.shape
)

Final results saved successfully.
(2481, 9)

In [18]:
check_results = pd.read_csv(
    "../data/processed/overall_candidate_ranking.csv"
)

print(check_results.shape)

check_results.head(10)

(2481, 9)

,overall_rank,ID,Category,match_score,skill_coverage,experience_score,overall_score,matched_skills,missing_skills
0,1,62994611,AGRICULTURE,21.273043,71.428571,100.0,64.953341,"['python', 'sql', 'javascript', 'react', 'mong...","['fastapi', 'rest api']"
1,2,83816738,INFORMATION-TECHNOLOGY,13.492720,42.857143,100.0,51.190673,"['javascript', 'mongodb', 'react']","['python', 'sql', 'fastapi', 'rest api']"
2,3,95429627,CONSULTANT,7.737766,42.857143,100.0,49.464187,"['python', 'sql', 'javascript']","['fastapi', 'mongodb', 'rest api', 'react']"
3,4,42156237,DIGITAL-MEDIA,14.860788,28.571429,100.0,45.886808,"['python', 'javascript']","['fastapi', 'sql', 'react', 'rest api', 'mongo..."
4,5,27152464,ENGINEERING,12.698314,28.571429,100.0,45.238066,"['python', 'mongodb']","['fastapi', 'sql', 'javascript', 'react', 'res..."
5,6,11981094,ENGINEERING,12.215554,28.571429,100.0,45.093238,"['javascript', 'rest api']","['python', 'fastapi', 'sql', 'react', 'mongodb']"
6,7,12011623,ENGINEERING,11.583866,28.571429,100.0,44.903731,"['python', 'sql']","['fastapi', 'javascript', 'react', 'rest api',..."
7,8,30863060,CONSULTANT,10.892236,28.571429,100.0,44.696242,"['sql', 'javascript']","['python', 'fastapi', 'react', 'rest api', 'mo..."
8,9,98300955,HEALTHCARE,10.555917,28.571429,100.0,44.595347,"['sql', 'javascript']","['python', 'fastapi', 'react', 'rest api', 'mo..."
9,10,12635195,INFORMATION-TECHNOLOGY,10.289198,28.571429,100.0,44.515331,"['python', 'javascript']","['fastapi', 'sql', 'react', 'rest api', 'mongo..."