In [1]:
import pandas as pd
import re

In [2]:
job_description = """
We are looking for a Python Developer with 3+ years of experience
in backend development.

The candidate should have strong knowledge of Python, FastAPI,
REST API, MongoDB, SQL, React and JavaScript.

Experience with Git, Docker and AWS is preferred.

The candidate should have a Bachelor's degree in Computer Science,
Information Technology or a related field.
"""

In [3]:
print(job_description)

We are looking for a Python Developer with 3+ years of experience
in backend development.

The candidate should have strong knowledge of Python, FastAPI,
REST API, MongoDB, SQL, React and JavaScript.

Experience with Git, Docker and AWS is preferred.

The candidate should have a Bachelor's degree in Computer Science,
Information Technology or a related field.

In [4]:
skills = [
    "python",
    "java",
    "c++",
    "javascript",
    "typescript",
    "html",
    "css",
    "react",
    "node.js",
    "nodejs",
    "express",
    "fastapi",
    "flask",
    "django",
    "sql",
    "mysql",
    "mongodb",
    "postgresql",
    "oracle",
    "redis",
    "git",
    "github",
    "docker",
    "aws",
    "azure",
    "linux",
    "excel",
    "power bi",
    "tableau",
    "pandas",
    "numpy",
    "scikit-learn",
    "tensorflow",
    "pytorch",
    "machine learning",
    "deep learning",
    "natural language processing",
    "nlp",
    "data analysis",
    "data visualization",
    "rest api",
    "rest",
    "api"
]

In [5]:
def extract_required_skills(text):
    found_skills = []
    text = text.lower()

    for skill in skills:
        if skill in text:
            found_skills.append(skill)

    found_skills.sort(key=len, reverse=True)

    final_skills = []

    for skill in found_skills:
        if not any(skill in existing for existing in final_skills):
            final_skills.append(skill)

    return final_skills

In [6]:
required_skills = extract_required_skills(job_description)

print(required_skills)

['javascript', 'rest api', 'fastapi', 'mongodb', 'python', 'docker', 'react', 'sql', 'git', 'aws']

In [7]:
def extract_required_experience(text):
    patterns = [
        r'(\d+(?:\.\d+)?)\+?\s+years?\s+of\s+experience',
        r'(\d+(?:\.\d+)?)\+?\s+years?\s+experience',
        r'(\d+(?:\.\d+)?)\+?\s+years?\s+in'
    ]

    for pattern in patterns:
        match = re.search(pattern, text, flags=re.IGNORECASE)

        if match:
            return float(match.group(1))

    return 0.0

In [8]:
required_experience = extract_required_experience(job_description)

print("Required Experience:", required_experience, "years")

Required Experience: 3.0 years

In [9]:
education_patterns = [
    r"\bBachelor'?s degree\b",
    r"\bMaster'?s degree\b",
    r"\bB\.Tech\b",
    r"\bB\.E\.\b",
    r"\bB\.Sc\.\b",
    r"\bB\.A\.\b",
    r"\bB\.Com\.\b",
    r"\bM\.Tech\b",
    r"\bM\.E\.\b",
    r"\bM\.Sc\.\b",
    r"\bMBA\b",
    r"\bMCA\b",
    r"\bPh\.D\.\b",
    r"\bBachelor of [A-Za-z ]+\b",
    r"\bMaster of [A-Za-z ]+\b"
]

In [10]:
def extract_required_education(text):
    education = []

    for pattern in education_patterns:
        matches = re.findall(
            pattern,
            text,
            flags=re.IGNORECASE
        )

        for match in matches:
            match = match.strip()

            if match.lower() not in [
                item.lower() for item in education
            ]:
                education.append(match)

    return education

In [11]:
required_education = extract_required_education(job_description)

print("Required Education:", required_education)

Required Education: ["Bachelor's degree"]

In [12]:
job_analysis = {
    "job_description": job_description,
    "required_skills": required_skills,
    "required_experience": required_experience,
    "required_education": required_education
}

job_analysis

{'job_description': "\nWe are looking for a Python Developer with 3+ years of experience\nin backend development.\n\nThe candidate should have strong knowledge of Python, FastAPI,\nREST API, MongoDB, SQL, React and JavaScript.\n\nExperience with Git, Docker and AWS is preferred.\n\nThe candidate should have a Bachelor's degree in Computer Science,\nInformation Technology or a related field.\n",
 'required_skills': ['javascript',
  'rest api',
  'fastapi',
  'mongodb',
  'python',
  'docker',
  'react',
  'sql',
  'git',
  'aws'],
 'required_experience': 3.0,
 'required_education': ["Bachelor's degree"]}

In [13]:
job_analysis_df = pd.DataFrame([job_analysis])

job_analysis_df

,job_description,required_skills,required_experience,required_education
0,\nWe are looking for a Python Developer with 3...,"[javascript, rest api, fastapi, mongodb, pytho...",3.0,[Bachelor's degree]

In [14]:
job_analysis_df.to_csv(
    "../data/processed/job_description_analysis.csv",
    index=False
)

In [15]:
pd.read_csv("../data/processed/job_description_analysis.csv")

,job_description,required_skills,required_experience,required_education
0,\nWe are looking for a Python Developer with 3...,"['javascript', 'rest api', 'fastapi', 'mongodb...",3.0,"[""Bachelor's degree""]"